INSERT INTO `ges_listados` VALUES ('', '(Debug) Log SQL', 'SELECT FechaCreacion as Fecha__FechaHora,TipoProceso as Tipo,Sql as Sentencia__decode64 FROM ges_logsql ORDER BY FechaCreacion DESC, Idlogsql DESC LIMIT 40', 'admin',0,'', 1);
;;;;;;
INSERT INTO `ges_listados` VALUES ('', 'USUARIOS', 'SELECT Nombre, Identificacion, Direccion, Telefono, IF(FechaNacim = ''0000-00-00'','''',DATE_FORMAT(FechaNacim,''%d/%m/%Y'')) AS ''Fecha Nacimiento'', ges_perfiles_usuario.NombrePerfil as Perfil, CuentaBanco as ''Cuenta Bancario'' \r\nFROM ges_usuarios \r\nINNER JOIN ges_perfiles_usuario ON ges_usuarios.IdPerfil = ges_perfiles_usuario.IdPerfil \r\nWHERE ges_usuarios.Eliminado=0 \r\nORDER BY Nombre ASC, Telefono DESC ', 'admin', 0, 'Listas', 0);
;;;;;;

INSERT INTO `ges_listados` VALUES ('', 'IMPORTE DE VENTAS POR PRODUCTOS', 'SELECT CONCAT(ges_productos_idioma.Descripcion,'' '',Marca,'' '',Color,'' '',Talla,'' '',NombreComercial) As Producto, SUM(ges_comprobantesdet.Cantidad) AS Cantidad, ROUND(SUM(ges_comprobantesdet.Importe),2) As Porc__Porcentaje, ROUND(SUM(ges_comprobantesdet.Importe),2) as Importe__Euro FROM ges_comprobantes INNER JOIN ges_comprobantesdet ON ges_comprobantes.IdComprobante = ges_comprobantesdet.IdComprobante INNER JOIN ges_productos ON ges_comprobantesdet.IdProducto = ges_productos.IdProducto INNER JOIN ges_productos_idioma ON ges_productos.IdProdBase = ges_productos_idioma.IdProdBase INNER JOIN ges_marcas ON ges_marcas.IdMarca = ges_productos.IdMarca INNER JOIN ges_laboratorios ON ges_laboratorios.IdLaboratorio = ges_productos.IdLabHab INNER JOIN ges_comprobantesnum ON ges_comprobantes.IdComprobante = ges_comprobantesnum.IdComprobante INNER JOIN ges_comprobantestipo ON ges_comprobantesnum.IdTipoComprobante = ges_comprobantestipo.IdTipoComprobante WHERE  ges_productos_idioma.IdIdioma = ''%IDIDIOMA%'' AND ges_comprobantes.FechaComprobante >= ''%DESDE%'' AND ges_comprobantes.FechaComprobante <= ''%HASTA%'' AND ges_comprobantes.IdLocal like ''%IDTIENDA%'' AND ges_comprobantestipo.TipoComprobante IN (''Factura'',''Boleta'',''Ticket'') AND ges_comprobantes.Eliminado = 0 GROUP BY ges_productos.IdProducto ORDER BY Importe__Euro DESC;', 'admin', 0, 'Ventas', 0);
;;;;;;

INSERT INTO `ges_listados` VALUES ('', 'CON STOCK ', 'SELECT  ges_locales.NombreComercial As Local,CodigoBarras As ''Código Barras'',Referencia, CONCAT(ges_productos_idioma.Descripcion,'' '', Marca,'' '', Color,'' '', Talla,'' '', ges_laboratorios.NombreComercial) As Producto, Unidades, ROUND(CostoUnitario) as Costo , ROUND(PrecioVenta,2) as PVP, ROUND(PrecioVentaCorporativo) as PVC, StockMin, Oferta \r\nFROM ges_almacenes INNER JOIN ges_productos ON ges_almacenes.IdProducto = ges_productos.IdProducto \r\nINNER JOIN ges_locales ON ges_almacenes.IdLocal = ges_locales.IdLocal\r\nINNER JOIN ges_productos_idioma ON ges_productos.IdProdBase = ges_productos_idioma.IdProdBase \r\nINNER JOIN ges_marcas ON ges_marcas.IdMarca = ges_productos.IdMarca \r\nINNER JOIN ges_modelos ON ges_modelos.IdColor = ges_productos.IdColor\r\nINNER JOIN ges_detalles on ges_detalles.IdTalla = ges_productos.IdTalla\r\nINNER JOIN ges_laboratorios ON ges_laboratorios.IdLaboratorio = ges_productos.IdLabHab \r\nWHERE  ges_almacenes.Unidades > 0\r\nAND ges_almacenes.Eliminado = 0 \r\nAND ges_locales.IdLocal like ''%IDTIENDA%''\r\nGROUP BY ges_productos.IdProducto \r\nORDER BY ges_productos_idioma.Descripcion;', 'admin', 0, 'Productos', 0);
;;;;;;

INSERT INTO `ges_listados` VALUES ('', 'OBSOLETOS ', 'SELECT ges_locales.NombreComercial AS Local,CodigoBarras As ''Código Barras'',Referencia, CONCAT(ges_productos_idioma.Descripcion,'' '', Marca,'' '', Color,'' '', Talla,'' '', ges_laboratorios.NombreComercial) As Producto, Unidades, ROUND(PrecioVenta,2) AS PrecioVenta, StockMin, Oferta \r\nFROM ges_almacenes INNER JOIN ges_productos ON ges_almacenes.IdProducto = ges_productos.IdProducto \r\nINNER JOIN ges_locales ON ges_almacenes.IdLocal = ges_locales.IdLocal\r\nINNER JOIN ges_productos_idioma ON ges_productos.IdProdBase = ges_productos_idioma.IdProdBase \r\nINNER JOIN ges_marcas ON ges_marcas.IdMarca = ges_productos.IdMarca \r\nINNER JOIN ges_modelos ON ges_modelos.IdColor = ges_productos.IdColor\r\nINNER JOIN ges_detalles on ges_detalles.IdTalla = ges_productos.IdTalla\r\nINNER JOIN ges_laboratorios ON ges_laboratorios.IdLaboratorio = ges_productos.IdLabHab \r\nWHERE  ges_almacenes.Unidades = 0\r\nAND ges_locales.IdLocal like ''%IDTIENDA%''\r\nAND ges_productos.Obsoleto = 1 \r\nGROUP BY ges_productos.IdProducto \r\nORDER BY ges_productos_idioma.Descripcion;', 'admin', 0, 'Productos', 0);
;;;;;;

INSERT INTO `ges_listados` VALUES ('', 'CON STOCK MINIMO ', 'SELECT  ges_locales.NombreComercial As Local,ges_proveedores.NombreComercial as Proveedor,CodigoBarras As ''Código Barras'',Referencia,CONCAT(ges_productos_idioma.Descripcion,'' '',Marca,'' '',Color,'' '',Talla,'' '',ges_laboratorios.NombreComercial) As Producto, Unidades, ROUND(CostoUnitario) as Costo , ROUND(PrecioVenta,2) as PVP, ROUND(PrecioVentaCorporativo) as PVC, StockMin, Oferta \r\nFROM ges_almacenes INNER JOIN ges_productos ON ges_almacenes.IdProducto=ges_productos.IdProducto \r\nINNER JOIN ges_locales ON ges_almacenes.IdLocal=ges_locales.IdLocal INNER JOIN ges_productos_idioma ON ges_productos.IdProdBase=ges_productos_idioma.IdProdBase INNER JOIN ges_marcas ON ges_marcas.IdMarca=ges_productos.IdMarca INNER JOIN ges_modelos ON ges_modelos.IdColor=ges_productos.IdColor INNER JOIN ges_detalles ON ges_detalles.IdTalla=ges_productos.IdTalla INNER JOIN ges_laboratorios ON ges_laboratorios.IdLaboratorio=ges_productos.IdLabHab INNER JOIN ges_proveedores ON ges_productos.IdProvHab = ges_proveedores.IdProveedor WHERE  ges_almacenes.StockMin>0 AND ges_almacenes.Unidades<=StockMin AND ges_locales.IdLocal like ''%IDTIENDA%'' AND ges_productos.IdProvHab like ''%IDPROVEEDOR%'' AND ges_almacenes.Eliminado=0 GROUP BY ges_productos.IdProducto ORDER BY ges_productos_idioma.Descripcion;', 'admin', 0, 'Productos', 0);
;;;;;;

INSERT INTO `ges_listados` VALUES ('', 'NUEVOS', 'SELECT  ges_locales.NombreComercial As Local, ges_comprobantesprov.TipoComprobante AS Documento, ges_comprobantesprov.Codigo AS ''Nro Doc.'', CodigoBarras AS CB,Referencia AS CR, CONCAT(ges_productos_idioma.Descripcion,'' '', Marca,'' '', Color,'' '', Talla,'' '', ges_laboratorios.NombreComercial) As Producto, ges_proveedores.NombreComercial AS Proveedor, ges_pedidosdet.Unidades,  DATE_FORMAT(ges_pedidos.FechaRecepcion,''%d/%m/%y %k:%i'') AS ''Fecha Compra'', ges_pedidosdet.Lote AS LT,  IF(DATE_FORMAT(ges_pedidosdet.FechaVencimiento,''%e-%b-%Y'') IS NULL,'' '',DATE_FORMAT(ges_pedidosdet.FechaVencimiento,''%d/%m/%y'')) AS FV\r\nFROM ges_pedidosdet INNER JOIN ges_productos ON ges_pedidosdet.IdProducto = ges_productos.IdProducto INNER JOIN ges_pedidos ON ges_pedidosdet.IdPedido = ges_pedidos.IdPedido INNER JOIN ges_locales ON ges_pedidos.IdLocal = ges_locales.IdLocal INNER JOIN ges_productos_idioma ON ges_productos.IdProdBase=ges_productos_idioma.IdProdBase INNER JOIN ges_marcas ON ges_productos.IdMarca = ges_marcas.IdMarca INNER JOIN ges_modelos ON ges_productos.IdColor  = ges_modelos.IdColor INNER JOIN ges_detalles ON ges_productos.IdTalla = ges_detalles.IdTalla INNER JOIN ges_laboratorios ON ges_productos.IdLabHab  = ges_laboratorios.IdLaboratorio INNER JOIN ges_comprobantesprov ON ges_pedidos.IdPedido = ges_comprobantesprov.IdPedido INNER JOIN ges_proveedores ON ges_comprobantesprov.IdProveedor = ges_proveedores.IdProveedor \r\n WHERE  DATE_SUB(CURDATE(),INTERVAL 15 DAY) <= ges_pedidos.FechaRecepcion AND ges_pedidos.IdLocal like ''%IDTIENDA%'' GROUP BY ges_productos.IdProducto HAVING COUNT(ges_pedidosdet.IdProducto)=1 ORDER BY ges_productos_idioma.Descripcion', 'admin', 0, 'Productos', 0);
;;;;;;

INSERT INTO `ges_listados` VALUES ('', 'EN OFERTA', 'SELECT  ges_locales.NombreComercial As Local,CodigoBarras As ''Código Barras'',Referencia,CONCAT(ges_productos_idioma.Descripcion,'' '',Marca,'' '',Color,'' '',Talla,'' '',ges_laboratorios.NombreComercial) As Producto, Unidades, ROUND(PrecioVenta,2) AS PrecioVenta, Oferta, ROUND(PrecioVentaOferta,2) as ''Precio Oferta''\r\nFROM ges_almacenes INNER JOIN ges_productos ON ges_almacenes.IdProducto=ges_productos.IdProducto \r\nINNER JOIN ges_locales ON ges_almacenes.IdLocal=ges_locales.IdLocal INNER JOIN ges_productos_idioma ON ges_productos.IdProdBase=ges_productos_idioma.IdProdBase INNER JOIN ges_marcas ON ges_marcas.IdMarca=ges_productos.IdMarca INNER JOIN ges_modelos ON ges_modelos.IdColor=ges_productos.IdColor INNER JOIN ges_detalles ON ges_detalles.IdTalla=ges_productos.IdTalla INNER JOIN ges_laboratorios ON ges_laboratorios.IdLaboratorio=ges_productos.IdLabHab WHERE  ges_almacenes.Oferta>0 AND ges_almacenes.Unidades>0 AND ges_almacenes.Eliminado=0 AND ges_almacenes.IdLocal like ''%IDTIENDA%'' ORDER BY ges_productos_idioma.Descripcion', 'admin', 0, 'Productos', 0);
;;;;;;


INSERT INTO `ges_listados` VALUES ('', 'EN OFERTA', 'SELECT  ges_locales.NombreComercial As Local,CodigoBarras As ''Código Barras'',Referencia,CONCAT(ges_productos_idioma.Descripcion,'' '',Marca,'' '',Color,'' '',Talla,'' '',ges_laboratorios.NombreComercial) As Producto, Unidades, ROUND(PrecioVenta,2) AS PrecioVenta, Oferta, ROUND(PrecioVentaOferta,2) as ''Precio Oferta''\r\nFROM ges_almacenes INNER JOIN ges_productos ON ges_almacenes.IdProducto=ges_productos.IdProducto \r\nINNER JOIN ges_locales ON ges_almacenes.IdLocal=ges_locales.IdLocal INNER JOIN ges_productos_idioma ON ges_productos.IdProdBase=ges_productos_idioma.IdProdBase INNER JOIN ges_marcas ON ges_marcas.IdMarca=ges_productos.IdMarca INNER JOIN ges_modelos ON ges_modelos.IdColor=ges_productos.IdColor INNER JOIN ges_detalles ON ges_detalles.IdTalla=ges_productos.IdTalla INNER JOIN ges_laboratorios ON ges_laboratorios.IdLaboratorio=ges_productos.IdLabHab WHERE  ges_almacenes.Oferta>0 AND ges_almacenes.Unidades>0 AND ges_almacenes.Eliminado=0 AND ges_almacenes.IdLocal = ''%IDTIENDA%'' ORDER BY ges_productos_idioma.Descripcion', 'TPV', 0, 'Productos', 0);
;;;;;;

INSERT INTO `ges_listados` VALUES ('', 'NUEVOS', 'SELECT ges_locales.NombreComercial As Local, Referencia AS CR, CONCAT(CodigoBarras,'' '',ges_productos_idioma.Descripcion,'' '', Marca,'' '', Color,'' '', Talla,'' '', ges_laboratorios.NombreComercial) As Producto, ges_pedidosdet.Unidades, ges_productos.UnidadMedida as ''UND Medida'', (SELECT ges_almacenes.''%TIPOVENTA%'' FROM ges_almacenes WHERE ges_almacenes.IdProducto = ges_pedidosdet.IdProducto AND ges_almacenes.IdLocal like ''%IDTIENDA%'') as Precio, ges_pedidosdet.Lote, IF(DATE_FORMAT(ges_pedidosdet.FechaVencimiento,''%e-%b-%Y'') IS NULL,'' '',DATE_FORMAT(ges_pedidosdet.FechaVencimiento,''%d/%m/%y'')) AS FV FROM ges_pedidosdet INNER JOIN ges_productos ON ges_pedidosdet.IdProducto = ges_productos.IdProducto INNER JOIN ges_pedidos ON ges_pedidosdet.IdPedido = ges_pedidos.IdPedido INNER JOIN ges_locales ON ges_pedidos.IdLocal = ges_locales.IdLocal INNER JOIN ges_productos_idioma ON ges_productos.IdProdBase=ges_productos_idioma.IdProdBase INNER JOIN ges_marcas ON ges_productos.IdMarca = ges_marcas.IdMarca INNER JOIN ges_modelos ON ges_productos.IdColor = ges_modelos.IdColor INNER JOIN ges_detalles ON ges_productos.IdTalla = ges_detalles.IdTalla INNER JOIN ges_laboratorios ON ges_productos.IdLabHab = ges_laboratorios.IdLaboratorio INNER JOIN ges_comprobantesprov ON ges_pedidos.IdPedido = ges_comprobantesprov.IdPedido INNER JOIN ges_proveedores ON ges_comprobantesprov.IdProveedor = ges_proveedores.IdProveedor WHERE DATE_SUB(CURDATE(),INTERVAL 15 DAY) <= ges_pedidos.FechaRecepcion AND ges_pedidos.IdLocal like ''%IDTIENDA%'' GROUP BY ges_productos.IdProducto HAVING COUNT(ges_pedidosdet.IdProducto)=1 ORDER BY ges_productos_idioma.Descripcion', 'TPV', 0, 'Productos', 0);
;;;;;;

INSERT INTO `ges_listados` VALUES ('', 'SIN STOCK', 'SELECT  ges_locales.NombreComercial As Local,Referencia as CR,CodigoBarras as CB,CONCAT(ges_productos_idioma.Descripcion,'' '',Marca,'' '',Color,'' '',Talla,'' '',ges_laboratorios.NombreComercial) As Producto, Unidades, ROUND(CostoUnitario) as Costo , ROUND(PrecioVenta,2) as PVP, ROUND(PrecioVentaCorporativo) as PVC, StockMin\r\nFROM ges_almacenes \r\nINNER JOIN ges_productos ON ges_almacenes.IdProducto=ges_productos.IdProducto \r\nINNER JOIN ges_locales ON ges_almacenes.IdLocal=ges_locales.IdLocal \r\nINNER JOIN ges_productos_idioma ON ges_productos.IdProdBase=ges_productos_idioma.IdProdBase \r\nINNER JOIN ges_marcas ON ges_marcas.IdMarca=ges_productos.IdMarca \r\nINNER JOIN ges_modelos ON ges_modelos.IdColor=ges_productos.IdColor \r\nINNER JOIN ges_detalles ON ges_detalles.IdTalla=ges_productos.IdTalla \r\nINNER JOIN ges_laboratorios ON ges_laboratorios.IdLaboratorio=ges_productos.IdLabHab \r\nWHERE  ges_almacenes.Unidades=0  AND ges_almacenes.Eliminado=0\r\nAND ges_locales.IdLocal like ''%IDTIENDA%'' \r\nGROUP BY ges_productos.IdProducto \r\nORDER BY ges_locales.IdLocal,ges_productos_idioma.Descripcion', 'admin', 0, 'Productos', 0);
;;;;;;

INSERT INTO `ges_listados` VALUES ('', 'POR USUARIO', 'SELECT ges_locales.NombreComercial as Local, ges_usuarios.Nombre as Usuario, COUNT(ges_comprobantes.IdUsuario) as Cantidad, ROUND(SUM(ges_comprobantes.TotalImporte),2) as ''Importe %SML%'' \r\nFROM ges_comprobantes \r\nINNER JOIN ges_usuarios ON ges_comprobantes.IdUsuario = ges_usuarios.IdUsuario \r\nINNER JOIN ges_locales ON ges_locales.IdLocal = ges_comprobantes.IdLocal\r\nINNER JOIN ges_comprobantesnum ON ges_comprobantes.IdComprobante = ges_comprobantesnum.IdComprobante\r\nINNER JOIN ges_comprobantestipo ON ges_comprobantesnum.IdTipoComprobante = ges_comprobantestipo.IdTipoComprobante\r\nWHERE ges_comprobantes.Eliminado = 0\r\nAND ges_comprobantestipo.TipoComprobante <> ''AlbaranInt''\r\nAND ges_comprobantestipo.TipoComprobante <> ''Albaran''\r\nAND ges_comprobantes.FechaComprobante >= ''%DESDE%''\r\nAND ges_comprobantes.FechaComprobante <= ''%HASTA%''\r\nAND ges_comprobantes.IdLocal like ''%IDTIENDA%''\r\nGROUP BY ges_comprobantes.IdUsuario', 'admin', 0, 'Ventas', 0);
;;;;;;

INSERT INTO `ges_listados` VALUES ('', 'CLIENTES FRECUENTES', 'SELECT ges_locales.NombreComercial as Local,ges_clientes.TipoCliente as ''Tipo Cliente'', IF(ges_clientes.TipoCliente = ''Empresa'',ges_clientes.NombreLegal,ges_clientes.NombreComercial) as CLiente, ges_clientes.NumeroFiscal as ''DNI/RUC'', COUNT(ges_comprobantes.IdCliente) as Cantidad, \r\nROUND(SUM(ges_comprobantes.TotalImporte),2) as ''Importe %SML%''\r\nFROM ges_comprobantes\r\nINNER JOIN ges_clientes ON ges_comprobantes.IdCliente = ges_clientes.IdCliente \r\nINNER JOIN ges_locales ON ges_comprobantes.IdLocal = ges_locales.IdLocal\r\nINNER JOIN ges_comprobantesnum ON ges_comprobantes.IdComprobante = ges_comprobantesnum.IdComprobante\r\nINNER JOIN ges_comprobantestipo ON ges_comprobantesnum.IdTipoComprobante = ges_comprobantestipo.IdTipoComprobante\r\nWHERE ges_comprobantes.Eliminado = 0\r\nAND ges_comprobantestipo.TipoComprobante <> ''AlbaranInt''\r\nAND ges_comprobantestipo.TipoComprobante <> ''Albaran''\r\nAND ges_comprobantes.FechaComprobante >= ''%DESDE%''\r\nAND ges_comprobantes.FechaComprobante <= ''%HASTA%''\r\nAND ges_comprobantes.IdLocal like ''%IDTIENDA%''\r\nAND ges_clientes.TipoCliente like ''%TIPOCLIENTE%''\r\nGROUP BY ges_locales.IdLocal,ges_comprobantes.IdCliente\r\nORDER BY ges_locales.IdLocal ASC,ges_clientes.TipoCliente ASC,Cantidad DESC', 'admin', 0, 'Ventas', 0);
;;;;;;

INSERT INTO `ges_listados` VALUES ('', 'CLIENTES FRECUENTES', 'SELECT ges_locales.NombreComercial as Local, ges_clientes.TipoCliente as ''Tipo Cliente'', IF(ges_clientes.TipoCliente = ''Empresa'',ges_clientes.NombreLegal,ges_clientes.NombreComercial) as CLiente, ges_clientes.NumeroFiscal as ''DNI/RUC'', COUNT(ges_comprobantes.IdCliente) as Cantidad, \r\nROUND(SUM(ges_comprobantes.TotalImporte),2) as ''Importe %SML%''\r\nFROM ges_comprobantes\r\nINNER JOIN ges_clientes ON ges_comprobantes.IdCliente = ges_clientes.IdCliente \r\nINNER JOIN ges_locales ON ges_comprobantes.IdLocal = ges_locales.IdLocal\r\nINNER JOIN ges_comprobantesnum ON ges_comprobantes.IdComprobante = ges_comprobantesnum.IdComprobante\r\nINNER JOIN ges_comprobantestipo ON ges_comprobantesnum.IdTipoComprobante = ges_comprobantestipo.IdTipoComprobante\r\nWHERE ges_comprobantes.Eliminado = 0\r\nAND ges_comprobantestipo.TipoComprobante <> ''AlbaranInt''\r\nAND ges_comprobantestipo.TipoComprobante <> ''Albaran''\r\nAND ges_comprobantes.FechaComprobante >= ''%DESDE%''\r\nAND ges_comprobantes.FechaComprobante <= ''%HASTA%''\r\nAND ges_comprobantes.IdLocal = ''%IDTIENDA%''\r\nAND ges_clientes.TipoCliente like ''%TIPOCLIENTE%''\r\nGROUP BY ges_comprobantes.IdCliente\r\nORDER BY ges_clientes.TipoCliente ASC,Cantidad DESC', 'TPV', 0, 'Ventas', 0);
;;;;;;

INSERT INTO `ges_listados` VALUES ('', 'PARTIDAS DE CAJA', 'SELECT TipoCaja, PartidaCaja, TipoOperacion,DATE_FORMAT(FechaRegistro,''%d/%m/%Y'') as FechaRegistro FROM ges_partidascaja WHERE FechaRegistro >=''%DESDE%'' AND FechaRegistro<=''%HASTA%'' \r\nOR (IdLocal = 0 OR IdLocal like ''%IDTIENDA%'') AND Eliminado = 0 ORDER BY FechaRegistro ASC', 'admin', 0, 'Listas', 0);
;;;;;;
INSERT INTO `ges_listados` VALUES ('', 'MOVIMIENTOS DE CAJA TPV', 'SELECT ges_usuarios.Identificacion AS Usuario, IF(IdPartidaCaja = 0,''Ventas'',(SELECT PartidaCaja FROM ges_partidascaja WHERE ges_partidascaja.IdPartidaCaja = ges_dinero_movimientos.IdPartidaCaja)) AS ''Partida'', DATE_FORMAT(FechaInsercion,''%d/%m/%Y %H:%s'') as ''Fecha Operacion'', ges_dinero_movimientos.TipoOperacion AS Operacion, Concepto, ROUND(Importe,2) AS ''Importe %SML%'' FROM ges_dinero_movimientos INNER JOIN ges_usuarios ON ges_dinero_movimientos.IdUsuario = ges_usuarios.IdUsuario WHERE ges_dinero_movimientos.Eliminado = 0 AND TipoVentaOperacion like ''%TIPOVENTAOP%'' AND DATE(FechaInsercion) >= ''%DESDE%'' AND DATE(FechaInsercion) <= ''%HASTA%''\r\nAND ges_dinero_movimientos.IdLocal like ''%IDTIENDA%''\r\nAND ges_dinero_movimientos.Importe > 0\r\nAND ges_dinero_movimientos.TipoOperacion like ''%TIPOOPERACION%''', 'admin', 0, 'Finanzas', 0);
;;;;;;

INSERT INTO `ges_listados` VALUES ('', 'PARTIDAS', 'SELECT PartidaCaja, TipoOperacion, DATE_FORMAT(FechaRegistro,''%d/%m/%Y %H:%s'') as FechaRegistro\r\nFROM ges_partidascaja\r\nWHERE Eliminado = 0 \r\nAND TipoCaja = ''%TIPOVENTA%'' \r\nAND FechaRegistro >= ''%DESDE%'' \r\nAND FechaRegistro <= ''%HASTA%'' \r\nAND IdLocal IN (0,''%IDLOCAL%'')', 'TPV', 0, 'Listas', 0);
;;;;;;

INSERT INTO `ges_listados` VALUES ('', 'COMPROBANTES', 'SELECT ges_locales.NombreComercial as Local, DATE_FORMAT(ges_comprobantesprov.FechaFacturacion,''%d/%m/%Y'') as ''Fecha Emisión'',ges_proveedores.NombreComercial as Proveedor, ges_comprobantesprov.Codigo as ''Serie-Nro'', ges_comprobantesprov.TipoComprobante as Comprobante, ges_comprobantesprov.EstadoPago as ''Estado Pago'', ges_moneda.Simbolo as Moneda,ROUND(ges_comprobantesprov.TotalImporte,2) as Importe, ROUND(ges_comprobantesprov.ImporteImpuesto,2) as Impuesto, ROUND(ges_comprobantesprov.ImportePercepcion,2) as Percepción, ROUND(ges_comprobantesprov.ImporteFlete,2) as Flete, ROUND(ges_comprobantesprov.ImportePago,2) as ''Importe Pago'', ROUND(ges_comprobantesprov.ImportePendiente,2) as Pendiente \r\nFROM ges_comprobantesprov \r\nINNER JOIN ges_pedidos ON ges_comprobantesprov.IdPedido =  ges_pedidos.IdPedido\r\nINNER JOIN ges_locales ON ges_pedidos.IdLocal = ges_locales.IdLocal\r\nINNER JOIN ges_moneda ON ges_pedidos.IdMoneda = ges_moneda.IdMoneda\r\nINNER JOIN ges_proveedores ON ges_comprobantesprov.IdProveedor = ges_proveedores.IdProveedor\r\nWHERE ges_comprobantesprov.Eliminado = 0\r\nAND ges_comprobantesprov.TipoComprobante <> ''AlbaranInt'' \r\nAND ges_comprobantesprov.EstadoPago <> ''Exonerado'' \r\nAND ges_comprobantesprov.FechaFacturacion >= ''%DESDE%''\r\nAND ges_comprobantesprov.FechaFacturacion <= ''%HASTA%''\r\nAND ges_pedidos.IdLocal like ''%IDTIENDA%''\r\nAND ges_comprobantesprov.IdProveedor like ''%IDPROVEEDOR%''\r\nAND ges_comprobantesprov.TipoComprobante like ''%TIPOCOMPROBANTE%''\r\nAND ges_comprobantesprov.EstadoDocumento like ''%ESTADOCOMPROBANTE%''\r\nAND ges_comprobantesprov.EstadoPago like ''%ESTADOPAGO%''\r\n', 'admin', 0, 'Compras', 0);
;;;;;;

INSERT INTO `ges_listados` VALUES ('', 'COMPROBANTES', 'SELECT ges_locales.NombreComercial as Local, DATE_FORMAT(ges_comprobantes.FechaComprobante,''%d/%m/%Y'') as ''Fecha Emisión'',IF(ges_clientes.TipoCliente = ''Empresa'',ges_clientes.NombreLegal,ges_clientes.NombreComercial) as Cliente, CONCAT(ges_comprobantestipo.Serie,'' - '',ges_comprobantesnum.NumeroComprobante) as ''Serie-Nro'', ges_comprobantestipo.TipoComprobante as Comprobante, ges_comprobantesnum.Status as ''Estado'', ROUND(ges_comprobantes.TotalImporte,2) as Importe, ROUND(ges_comprobantes.ImporteImpuesto,2) as Impuesto,  ROUND(ges_comprobantes.ImportePendiente,2) as Pendiente \r\nFROM ges_comprobantes\r\nINNER JOIN ges_locales ON ges_comprobantes.IdLocal = ges_locales.IdLocal\r\nINNER JOIN ges_comprobantesnum ON ges_comprobantes.IdComprobante =  ges_comprobantesnum.IdComprobante\r\nINNER JOIN ges_comprobantestipo ON ges_comprobantesnum.IdTipoComprobante = ges_comprobantestipo.IdTipoComprobante \r\nINNER JOIN ges_clientes ON ges_comprobantes.IdCliente = ges_clientes.IdCliente \r\nWHERE ges_comprobantes.Eliminado = 0\r\nAND ges_comprobantestipo.TipoComprobante IN (''Factura'',''Boleta'',''Ticket'',''Albaran'')\r\nAND DATE(ges_comprobantesnum.Fecha) >= ''%DESDE%''\r\nAND DATE(ges_comprobantesnum.Fecha) <= ''%HASTA%''\r\nAND ges_comprobantes.IdLocal  like ''%IDTIENDA%''\r\nAND ges_comprobantestipo.Serie like ''%SERIECOMPROBANTE%'' \r\nAND ges_comprobantestipo.TipoComprobante like ''%TIPOCOMPROBANTE%''\r\n AND ges_comprobantes.ImportePendiente ''%IMPORTE%''\r\n', 'admin', 0, 'Ventas', 0);
;;;;;;

INSERT INTO `ges_listados` VALUES ('', 'PRODUCTOS ANOTADOS', 'SELECT ges_locales.NombreComercial as Local, DATE_FORMAT(ges_productosborrador.FechaRegistro,''%d/%m/%Y %H:%i'') as ''Fecha Registro'', ProductoBorrador as Producto, ges_usuarios.Identificacion as Usuario \r\nFROM ges_productosborrador\r\nINNER JOIN ges_locales ON ges_productosborrador.IdLocal = ges_locales.IdLocal\r\nINNER JOIN ges_usuarios ON ges_productosborrador.IdUsuario = ges_usuarios.IdUsuario\r\nWHERE DATE(ges_productosborrador.FechaRegistro) >= ''%DESDE%''\r\nAND DATE(ges_productosborrador.FechaRegistro) <= ''%HASTA%''\r\nAND ges_productosborrador.IdLocal like ''%IDTIENDA%''\r\nAND ges_productosborrador.Eliminado = 0', 'admin', 0, 'Listas', 0);
;;;;;;

INSERT INTO `ges_listados` VALUES ('', 'PRODUCTOS ANOTADOS', 'SELECT ges_locales.NombreComercial as Local, DATE_FORMAT(ges_productosborrador.FechaRegistro,''%d/%m/%Y %H:%i'') as ''Fecha Registro'', ProductoBorrador as Producto, ges_usuarios.Identificacion as Usuario \r\nFROM ges_productosborrador\r\nINNER JOIN ges_locales ON ges_productosborrador.IdLocal = ges_locales.IdLocal\r\nINNER JOIN ges_usuarios ON ges_productosborrador.IdUsuario = ges_usuarios.IdUsuario\r\nWHERE DATE(ges_productosborrador.FechaRegistro) >= ''%DESDE%''\r\nAND DATE(ges_productosborrador.FechaRegistro) <= ''%HASTA%''\r\nAND ges_productosborrador.IdLocal = ''%IDTIENDA%''\r\nAND ges_productosborrador.Eliminado = 0', 'TPV', 0, 'Listas', 0);
;;;;;;

INSERT INTO `ges_listados` VALUES ('', 'PROMOCIONES', 'SELECT ges_locales.NombreComercial as Local, DATE_FORMAT(ges_promociones.FechaRegistro,''%d/%m/%Y %H:%i'') as ''Fecha Registro'', ges_promociones.Descripcion, DATE_FORMAT(FechaInicio,''%d/%m/%Y %H:%i'') as ''Fecha Inicio'',DATE_FORMAT(FechaFin,''%d/%m/%Y %H:%i'') as ''Fecha Fin'', ges_promociones.Estado, IF(ges_promociones.Modalidad = ''MontoCompra'',''Monto Compra'',''Historial Compra'') as Modalidad, MontoCompraActual as ''Monto Compra'', ges_promociones.Tipo, IF(CBProducto0 = 0,'''',CBProducto0 ) as ''CB Producto'', IF(CBProducto1 = 0,'''',CBProducto1) as ''CB Producto Alternativa'', IF(ges_promociones.Descuento = 0,'''',ges_promociones.Descuento) as ''Descuento(%)'', IF(Bono = 0,'''',Bono) as Bono\r\nFROM ges_promociones\r\nINNER JOIN ges_locales ON ges_promociones.IdLocal = ges_locales.IdLocal\r\nWHERE ges_promociones.Eliminado = 0\r\nAND DATE(ges_promociones.FechaRegistro) >= ''%DESDE%''\r\nAND DATE(ges_promociones.FechaRegistro) <= ''%HASTA%''\r\nAND ges_promociones.IdLocal  like ''%IDTIENDA%''\r\nAND ges_promociones.Modalidad like ''%MODALIDAD%'' \r\nAND ges_promociones.Estado like ''%ESTADOPROMO%''\r\nAND ges_promociones.Tipo like ''%TIPOPROMO%''', 'admin', 0, 'Ventas', 0);
;;;;;;

INSERT INTO `ges_listados` VALUES ('', 'PROMOCIONES', 'SELECT ges_locales.NombreComercial as Local, DATE_FORMAT(ges_promociones.FechaRegistro,''%d/%m/%Y %H:%i'') as ''Fecha Registro'', ges_promociones.Descripcion, DATE_FORMAT(FechaInicio,''%d/%m/%Y %H:%i'') as ''Fecha Inicio'',DATE_FORMAT(FechaFin,''%d/%m/%Y %H:%i'') as ''Fecha Fin'', ges_promociones.Estado, IF(ges_promociones.Modalidad = ''MontoCompra'',''Monto Compra'',''Historial Compra'') as Modalidad, MontoCompraActual as ''Monto Compra'', ges_promociones.Tipo, IF(CBProducto0 = 0,'''',CBProducto0 ) as ''CB Producto'', IF(CBProducto1 = 0,'''',CBProducto1) as ''CB Producto Alternativa'', IF(ges_promociones.Descuento = 0,'''',ges_promociones.Descuento) as ''Descuento(%)'', IF(Bono = 0,'''',Bono) as Bono\r\nFROM ges_promociones\r\nINNER JOIN ges_locales ON ges_promociones.IdLocal = ges_locales.IdLocal\r\nWHERE ges_promociones.Eliminado = 0\r\nAND DATE(ges_promociones.FechaRegistro) >= ''%DESDE%''\r\nAND DATE(ges_promociones.FechaRegistro) <= ''%HASTA%''\r\nAND ges_promociones.IdLocal  = ''%IDTIENDA%''\r\nAND ges_promociones.Modalidad like ''%MODALIDAD%'' \r\nAND ges_promociones.Estado = ''Ejecucion''\r\nAND ges_promociones.Tipo like ''%TIPOPROMO%''', 'TPV', 0, 'Ventas', 0);
;;;;;;

INSERT INTO `ges_listados` VALUES ('', 'ARQUEO CAJA TPV', 'SELECT ges_locales.NombreComercial as Local, IF(TipoVentaOperacion=''VD'',''B2C'',''B2B'') as ''Tipo Venta'', DATE_FORMAT(FechaCierre,''%d/%m/%Y %H:%i'') AS ''Fecha Cierre'', ROUND(ImporteApertura,2) as ''Importe Apertura'', ROUND(ImporteIngresos,2) as ''Importe Ingreso'', ROUND(ImporteGastos,2) as ''Importe Gastos'', ROUND(ImporteAportaciones,2) as ''Importe Aportacion'', ROUND(ImporteSustracciones,2) as ''Importe Sustraccion'', ROUND(ImporteTeoricoCierre,2) as ''Importe Teorico Cierre'', ROUND(ImporteCierre,2) as ''Importe Cierre'',  ROUND(ImporteDescuadre,2) as ''Importe Descuadre'', ROUND(UtilidadVenta,2) as ''Utilidad Venta''  FROM ges_arqueo_caja  INNER JOIN ges_locales ON ges_arqueo_caja.IdLocal = ges_locales.IdLocal \r\nWHERE ges_arqueo_caja.Eliminado = 0 AND TipoVentaOperacion like ''%TIPOVENTAOP%'' AND ges_arqueo_caja.IdLocal like ''%IDTIENDA%'' AND DATE(FechaCierre) >= ''%DESDE%'' AND DATE(FechaCierre) <= ''%HASTA%''', 'admin', 0, 'Finanzas', 0);
;;;;;;


INSERT INTO `ges_listados` VALUES ('', 'MOVIMIENTOS DE PARTIDAS CAJA TPV', 'SELECT ges_usuarios.Identificacion as Usuario,DATE_FORMAT(FechaInsercion,''%d/%m/%Y %H:%s'') as ''Fecha Operacion'', PartidaCaja as ''Partida Caja'',ges_dinero_movimientos.TipoOperacion as Operacion,Concepto, ROUND(ges_dinero_movimientos.Importe,2) as ''Importe %SML%''\r\nFROM ges_dinero_movimientos\r\nINNER JOIN ges_partidascaja ON ges_dinero_movimientos.IdPartidaCaja = ges_partidascaja.IdPartidaCaja\r\nINNER JOIN ges_usuarios ON ges_dinero_movimientos.IdUsuario = ges_usuarios.IdUsuario\r\nWHERE ges_dinero_movimientos.Eliminado = 0\r\nAND ges_dinero_movimientos.IdPartidaCaja like ''%PARTIDA%''\r\nAND ges_dinero_movimientos.IdLocal like ''%IDTIENDA%''\r\nAND DATE(FechaInsercion) >= ''%DESDE%'' \r\nAND DATE(FechaInsercion) <= ''%HASTA%''\r\nAND ges_dinero_movimientos.IdTbjoSubsidiario <> 0', 'admin', 0, 'Finanzas', 0);
;;;;;;

INSERT INTO `ges_listados` VALUES ('', 'CON MAYOR MOVIMIENTO', 'SELECT ges_locales.NombreComercial as Local, ges_comprobantesdet.CodigoBarras as ''Código Barras'', ges_comprobantesdet.Referencia, CONCAT(ges_productos_idioma.Descripcion,'' '',Marca,'' '',Color,'' '',Talla,'' '',ges_laboratorios.NombreComercial) As Producto, SUM(ges_comprobantesdet.Cantidad) AS Cantidad, ROUND(AVG(ges_comprobantesdet.Precio),2) As ''Precio Promedio''\r\nFROM ges_comprobantes \r\nINNER JOIN ges_comprobantesdet ON ges_comprobantes.IdComprobante = ges_comprobantesdet.IdComprobante \r\nINNER JOIN ges_productos ON ges_comprobantesdet.IdProducto = ges_productos.IdProducto \r\nINNER JOIN ges_productos_idioma ON ges_productos.IdProdBase = ges_productos_idioma.IdProdBase \r\nINNER JOIN ges_familias ON ges_productos.IdFamilia = ges_familias.IdFamilia\r\nINNER JOIN ges_marcas ON ges_marcas.IdMarca = ges_productos.IdMarca \r\nINNER JOIN ges_laboratorios ON ges_laboratorios.IdLaboratorio = ges_productos.IdLabHab \r\nINNER JOIN ges_comprobantesnum ON ges_comprobantes.IdComprobante = ges_comprobantesnum.IdComprobante \r\nINNER JOIN ges_comprobantestipo ON ges_comprobantesnum.IdTipoComprobante = ges_comprobantestipo.IdTipoComprobante \r\nINNER JOIN ges_locales ON ges_comprobantes.IdLocal = ges_locales.IdLocal\r\nAND ges_comprobantes.FechaComprobante >= ''%DESDE%'' \r\nAND ges_comprobantes.FechaComprobante <= ''%HASTA%'' \r\nAND ges_comprobantes.IdLocal like ''%IDTIENDA%'' \r\nAND ges_productos.IdFamilia like ''%IDFAMILIA%''\r\nAND ges_productos.IdMarca like ''%IDMARCA%''\r\nAND ges_comprobantestipo.TipoComprobante IN (''Factura'',''Boleta'',''Ticket'') \r\nAND ges_comprobantes.Eliminado = 0 \r\nGROUP BY ges_productos.IdProducto,ges_locales.Idlocal \r\nORDER BY ges_locales.IdLocal,Cantidad DESC\r\n', 'admin', 0, 'Productos', 0);
;;;;;;

INSERT INTO `ges_listados` VALUES ('', 'POR PRODUCTO', 'SELECT ges_locales.NombreComercial as Local, DATE_FORMAT(ges_comprobantesnum.Fecha,''%d/%m/%Y %H:%i'') as ''Fecha Operacion'', ges_comprobantesdet.CodigoBarras as ''Código Barras'', ges_comprobantesdet.Referencia, CONCAT(ges_productos_idioma.Descripcion,'' '',Marca,'' '',Color,'' '',Talla,'' '',ges_laboratorios.NombreComercial) As Producto, ges_comprobantestipo.TipoComprobante as Comprobante, CONCAT(ges_comprobantestipo.Serie,'' - '',ges_comprobantesnum.NumeroComprobante) as Código, ges_comprobantesdet.Cantidad, ROUND(ges_comprobantesdet.Precio,2) as Precio, ROUND(ges_comprobantesdet.Importe,2)\r\nFROM ges_comprobantes \r\nINNER JOIN ges_comprobantesdet ON ges_comprobantes.IdComprobante = ges_comprobantesdet.IdComprobante \r\nINNER JOIN ges_productos ON ges_comprobantesdet.IdProducto = ges_productos.IdProducto \r\nINNER JOIN ges_productos_idioma ON ges_productos.IdProdBase = ges_productos_idioma.IdProdBase \r\nINNER JOIN ges_familias ON ges_productos.IdFamilia = ges_familias.IdFamilia\r\nINNER JOIN ges_marcas ON ges_marcas.IdMarca = ges_productos.IdMarca \r\nINNER JOIN ges_laboratorios ON ges_laboratorios.IdLaboratorio = ges_productos.IdLabHab \r\nINNER JOIN ges_comprobantesnum ON ges_comprobantes.IdComprobante = ges_comprobantesnum.IdComprobante \r\nINNER JOIN ges_comprobantestipo ON ges_comprobantesnum.IdTipoComprobante = ges_comprobantestipo.IdTipoComprobante \r\nINNER JOIN ges_locales ON ges_comprobantes.IdLocal = ges_locales.IdLocal\r\nAND ges_comprobantes.FechaComprobante >= ''%DESDE%'' \r\nAND ges_comprobantes.FechaComprobante <= ''%HASTA%'' \r\nAND ges_comprobantes.IdLocal like ''%IDTIENDA%'' \r\nAND ges_comprobantesdet.CodigoBarras like ''%CODIGOBARRAS%''\r\nAND ges_comprobantestipo.TipoComprobante IN (''Factura'',''Boleta'',''Ticket'') \r\nAND ges_comprobantes.Eliminado = 0 \r\nORDER BY ges_locales.IdLocal,ges_comprobantes.IdComprobante ASC\r\n', 'admin', 0, 'Ventas', 0);
;;;;;;

INSERT INTO `ges_listados` VALUES ('', 'POR CLIENTES', 'SELECT ges_locales.NombreComercial as Local, DATE_FORMAT(ges_comprobantesnum.Fecha,''%d/%m/%Y %H:%i'') as ''Fecha Operacion'',ges_clientes.TipoCliente AS ''Tipo Cliente'', IF(ges_clientes.TipoCliente = ''Empresa'',ges_clientes.NombreLegal,ges_clientes.NombreComercial) as Cliente, ges_clientes.NumeroFiscal as ''DNI/RUC'', ges_comprobantestipo.TipoComprobante as Comprobante, CONCAT(ges_comprobantestipo.Serie,'' - '',ges_comprobantesnum.NumeroComprobante) as Código, ROUND(ges_comprobantes.TotalImporte,2) as ''Importe %SML%'', ROUND(ges_comprobantes.ImportePendiente,2) as ''Pendiente %SML%''\r\nFROM ges_comprobantes \r\nINNER JOIN ges_comprobantesnum ON ges_comprobantes.IdComprobante = ges_comprobantesnum.IdComprobante \r\nINNER JOIN ges_comprobantestipo ON ges_comprobantesnum.IdTipoComprobante = ges_comprobantestipo.IdTipoComprobante \r\nINNER JOIN ges_locales ON ges_comprobantes.IdLocal = ges_locales.IdLocal\r\nINNER JOIN ges_clientes ON ges_comprobantes.IdCliente = ges_clientes.IdCliente\r\nAND ges_comprobantes.FechaComprobante >= ''%DESDE%'' \r\nAND ges_comprobantes.FechaComprobante <= ''%HASTA%'' \r\nAND ges_comprobantes.IdLocal like ''%IDTIENDA%'' \r\nAND ges_clientes.NumeroFiscal like ''%DNICLIENTE%''\r\nAND ges_clientes.NombreComercial like ''%CLIENTE%''\r\nAND ges_clientes.TipoCliente like ''%TIPOCLIENTE%''\r\nAND ges_comprobantestipo.TipoComprobante IN (''Factura'',''Boleta'',''Ticket'') \r\nAND ges_comprobantes.Eliminado = 0 \r\nAND ges_clientes.TipoCliente <> ''Interno''\r\nORDER BY ges_locales.IdLocal,ges_comprobantes.IdComprobante ASC\r\n', 'admin', 0, 'Ventas', 0);
;;;;;;

INSERT INTO `ges_listados` VALUES ('', 'POR PERIODOS', 'SELECT ges_locales.NombreComercial as Local, YEAR(FechaComprobante) as ANIO,\r\nIF(''%PERIODOVENTA%''=''YEAR'',\r\n    '''',\r\n    (DATE_FORMAT(FechaComprobante,''%M''))\r\n) as MES, \r\nIF(''%PERIODOVENTA%'' IN (''MONTH'',''YEAR''),\r\n   '''',\r\n   (IF(''%PERIODOVENTA%''=''WEEK'',\r\n       (GROUP_CONCAT(DISTINCT(DAY(FechaComprobante)))),\r\n       (DAY(FechaComprobante)) \r\n      )\r\n   )\r\n) AS DIA, ROUND(SUM(ges_comprobantes.TotalImporte),2) as Importe \r\nFROM ges_comprobantes \r\nINNER JOIN ges_comprobantesnum ON ges_comprobantes.IdComprobante = ges_comprobantesnum.IdComprobante\r\nINNER JOIN ges_comprobantestipo ON ges_comprobantesnum.IdTipoComprobante = ges_comprobantestipo.IdTipoComprobante\r\nINNER JOIN ges_locales ON ges_comprobantes.IdLocal = ges_locales.IdLocal\r\nWHERE ges_comprobantestipo.TipoComprobante IN (''Factura'',''Boleta'',''Ticket'')\r\nAND ges_comprobantesnum.Status <> ''Anulado''\r\nAND ges_comprobantes.Eliminado = 0\r\nAND ges_comprobantes.FechaComprobante >= ''%DESDE%''\r\nAND ges_comprobantes.FechaComprobante <= ''%HASTA%''\r\nAND ges_comprobantes.IdLocal like ''%IDTIENDA%''\r\nGROUP BY  ''%PERIODO_GROUP%''\r\nORDER BY ges_locales.IdLocal,ges_comprobantes.FechaComprobante ASC', 'admin', 0, 'Ventas', 0);
;;;;;;

INSERT INTO `ges_listados` VALUES ('', 'CLIENTES', 'SELECT IF(ges_clientes.IdLocal = 0,''GENERAL'',(SELECT ges_locales.NombreComercial FROM ges_locales WHERE ges_locales.IdLocal = ges_clientes.IdLocal)) as Local, TipoCliente as ''TipoCliente'', IF(TipoCliente IN (''Empresa'',''Gobierno''),ges_clientes.NombreLegal,ges_clientes.NombreComercial) as Cliente, DATE_FORMAT(ges_clientes.FechaRegistro,''%d/%m/%Y'') as ''Fecha Registro'', ges_clientes.NumeroFiscal as ''DNI/RUC'', ges_clientes.Direccion, ges_clientes.Telefono1 as ''Teléfono'', ges_clientes.Email, ROUND(ges_clientes.Descuento,2) as ''Descuento'', ROUND(Bono,2) as ''Bono''\r\nFROM ges_clientes\r\nWHERE ges_clientes.Eliminado = 0\r\nAND ges_clientes.IdCliente > 0\r\nAND TipoCliente <>''Interno''\r\nAND ges_clientes.IdLocal like ''%IDTIENDA%''\r\nORDER BY ges_clientes.FechaRegistro', 'admin', 0, 'Listas', 0);
;;;;;;

INSERT INTO `ges_listados` VALUES ('', 'DEUDAS', 'SELECT ges_locales.NombreComercial as Local, DATE_FORMAT(ges_comprobantes.FechaComprobante,''%d/%m/%Y'') as ''Fecha Emisión'',IF(ges_clientes.TipoCliente = ''Empresa'',ges_clientes.NombreLegal,ges_clientes.NombreComercial) as Cliente, CONCAT(ges_comprobantestipo.Serie,'' - '',ges_comprobantesnum.NumeroComprobante) as ''Serie-Nro'', ges_comprobantestipo.TipoComprobante as Comprobante, ROUND(ges_comprobantes.TotalImporte,2) as Importe, ROUND(ges_comprobantes.ImportePendiente,2) as Pendiente, ges_comprobantes.Cobranza as ''Estado Cobranza'', DATE_FORMAT(ges_comprobantes.PlazoPago,''%d/%m/%Y'') as ''Plazo Pago'', ges_comprobantes.Observaciones\r\nFROM ges_comprobantes\r\nINNER JOIN ges_locales ON ges_comprobantes.IdLocal = ges_locales.IdLocal\r\nINNER JOIN ges_comprobantesnum ON ges_comprobantes.IdComprobante =  ges_comprobantesnum.IdComprobante\r\nINNER JOIN ges_comprobantestipo ON ges_comprobantesnum.IdTipoComprobante = ges_comprobantestipo.IdTipoComprobante \r\nINNER JOIN ges_clientes ON ges_comprobantes.IdCliente = ges_clientes.IdCliente \r\nWHERE ges_comprobantes.Eliminado = 0\r\nAND ges_comprobantes.ImportePendiente > 0\r\nAND ges_comprobantestipo.TipoComprobante IN (''Factura'',''Boleta'',''Ticket'',''Albaran'')\r\nAND DATE(ges_comprobantesnum.Fecha) >= ''%DESDE%''\r\nAND DATE(ges_comprobantesnum.Fecha) <= ''%HASTA%''\r\nAND ges_comprobantes.IdLocal  like ''%IDTIENDA%''\r\nAND ges_comprobantestipo.TipoComprobante like ''%TIPOCOMPROBANTE%''\r\nAND ges_comprobantes.Cobranza like ''%COBRANZA%''', 'admin', 0, 'Ventas', 0)
;;;;;;

INSERT INTO `ges_listados` VALUES ('', 'DEUDAS', 'SELECT ges_locales.NombreComercial as Local, DATE_FORMAT(ges_comprobantes.FechaComprobante,''%d/%m/%Y'') as ''Fecha Emisión'',IF(ges_clientes.TipoCliente = ''Empresa'',ges_clientes.NombreLegal,ges_clientes.NombreComercial) as Cliente, CONCAT(ges_comprobantestipo.Serie,'' - '',ges_comprobantesnum.NumeroComprobante) as ''Serie-Nro'', ges_comprobantestipo.TipoComprobante as Comprobante, ROUND(ges_comprobantes.TotalImporte,2) as Importe, ROUND(ges_comprobantes.ImportePendiente,2) as Pendiente, ges_comprobantes.Cobranza as ''Estado Cobranza'', DATE_FORMAT(ges_comprobantes.PlazoPago,''%d/%m/%Y'') as ''Plazo Pago'', ges_comprobantes.Observaciones\r\nFROM ges_comprobantes\r\nINNER JOIN ges_locales ON ges_comprobantes.IdLocal = ges_locales.IdLocal\r\nINNER JOIN ges_comprobantesnum ON ges_comprobantes.IdComprobante =  ges_comprobantesnum.IdComprobante\r\nINNER JOIN ges_comprobantestipo ON ges_comprobantesnum.IdTipoComprobante = ges_comprobantestipo.IdTipoComprobante \r\nINNER JOIN ges_clientes ON ges_comprobantes.IdCliente = ges_clientes.IdCliente \r\nWHERE ges_comprobantes.Eliminado = 0\r\nAND ges_comprobantes.ImportePendiente > 0\r\nAND ges_comprobantestipo.TipoComprobante IN (''Factura'',''Boleta'',''Ticket'',''Albaran'')\r\nAND DATE(ges_comprobantesnum.Fecha) >= ''%DESDE%''\r\nAND DATE(ges_comprobantesnum.Fecha) <= ''%HASTA%''\r\nAND ges_comprobantes.IdLocal  like ''%IDTIENDA%''\r\nAND ges_comprobantestipo.TipoComprobante like ''%TIPOCOMPROBANTE%''\r\nAND ges_comprobantes.Cobranza like ''%COBRANZA%''', 'TPV', 0, 'Ventas', 0);
;;;;;;

INSERT INTO `ges_listados` VALUES ('', 'DEVOLUCIONES', 'SELECT  ges_locales.NombreComercial As Local,ges_comprobantesdet.Referencia as CR,ges_comprobantesdet.CodigoBarras as CB,CONCAT(ges_productos_idioma.Descripcion,'' '',Marca,'' '',ges_comprobantesdet.Color,'' '',ges_comprobantesdet.Talla,'' '',ges_laboratorios.NombreComercial) As Producto, ges_comprobantestipo.TipoComprobante as Comprobante, CONCAT(ges_comprobantestipo.Serie,''-'',ges_comprobantesnum.NumeroComprobante) as Código, ges_comprobantesdet.CantidadDevolucion as Devolución, ges_comprobantesdet.Precio, ges_clientes.NombreComercial as Cliente, ges_usuarios.Identificacion as Usuario\r\nFROM ges_comprobantesdet\r\nINNER JOIN ges_comprobantes ON ges_comprobantesdet.IdComprobante = ges_comprobantes.IdComprobante\r\nINNER JOIN ges_productos ON ges_comprobantesdet.IdProducto=ges_productos.IdProducto \r\nINNER JOIN ges_locales ON ges_comprobantes.IdLocal=ges_locales.IdLocal \r\nINNER JOIN ges_productos_idioma ON ges_productos.IdProdBase=ges_productos_idioma.IdProdBase \r\nINNER JOIN ges_marcas ON ges_marcas.IdMarca=ges_productos.IdMarca \r\nINNER JOIN ges_modelos ON ges_modelos.IdColor=ges_productos.IdColor \r\nINNER JOIN ges_detalles ON ges_detalles.IdTalla=ges_productos.IdTalla \r\nINNER JOIN ges_laboratorios ON ges_laboratorios.IdLaboratorio=ges_productos.IdLabHab \r\nINNER JOIN ges_comprobantesnum ON ges_comprobantes.IdComprobante = ges_comprobantesnum.IdComprobante \r\nINNER JOIN ges_comprobantestipo ON ges_comprobantesnum.IdTipoComprobante = ges_comprobantestipo.IdTipoComprobante\r\nINNER JOIN ges_clientes ON ges_comprobantes.IdCliente = ges_clientes.IdCliente\r\nINNER JOIN ges_usuarios ON ges_comprobantes.IdUsuario = ges_usuarios.IdUsuario\r\nWHERE ges_comprobantesdet.CantidadDevolucion > 0\r\nAND ges_comprobantes.FechaComprobante >= ''%DESDE%''\r\nAND ges_comprobantes.FechaComprobante <= ''%HASTA%''\r\nAND ges_locales.IdLocal like ''%IDTIENDA%''\r\nAND ges_comprobantestipo.TipoComprobante IN (''Factura'',''Boleta'',''Ticket'')', 'admin', 0, 'Ventas', 0);
;;;;;;

INSERT INTO `ges_listados` VALUES ('', 'DEVOLUCIONES', 'SELECT  ges_locales.NombreComercial As Local,ges_comprobantesdet.Referencia as CR,ges_comprobantesdet.CodigoBarras as CB,CONCAT(ges_productos_idioma.Descripcion,'' '',Marca,'' '',ges_comprobantesdet.Color,'' '',ges_comprobantesdet.Talla,'' '',ges_laboratorios.NombreComercial) As Producto, ges_comprobantestipo.TipoComprobante as Comprobante, CONCAT(ges_comprobantestipo.Serie,''-'',ges_comprobantesnum.NumeroComprobante) as Código, ges_comprobantesdet.CantidadDevolucion as Devolución, ges_comprobantesdet.Precio, ges_clientes.NombreComercial as Cliente, ges_usuarios.Identificacion as Usuario\r\nFROM ges_comprobantesdet\r\nINNER JOIN ges_comprobantes ON ges_comprobantesdet.IdComprobante = ges_comprobantes.IdComprobante\r\nINNER JOIN ges_productos ON ges_comprobantesdet.IdProducto=ges_productos.IdProducto \r\nINNER JOIN ges_locales ON ges_comprobantes.IdLocal=ges_locales.IdLocal \r\nINNER JOIN ges_productos_idioma ON ges_productos.IdProdBase=ges_productos_idioma.IdProdBase \r\nINNER JOIN ges_marcas ON ges_marcas.IdMarca=ges_productos.IdMarca \r\nINNER JOIN ges_modelos ON ges_modelos.IdColor=ges_productos.IdColor \r\nINNER JOIN ges_detalles ON ges_detalles.IdTalla=ges_productos.IdTalla \r\nINNER JOIN ges_laboratorios ON ges_laboratorios.IdLaboratorio=ges_productos.IdLabHab \r\nINNER JOIN ges_comprobantesnum ON ges_comprobantes.IdComprobante = ges_comprobantesnum.IdComprobante \r\nINNER JOIN ges_comprobantestipo ON ges_comprobantesnum.IdTipoComprobante = ges_comprobantestipo.IdTipoComprobante\r\nINNER JOIN ges_clientes ON ges_comprobantes.IdCliente = ges_clientes.IdCliente\r\nINNER JOIN ges_usuarios ON ges_comprobantes.IdUsuario = ges_usuarios.IdUsuario\r\nWHERE ges_comprobantesdet.CantidadDevolucion > 0\r\nAND ges_comprobantes.FechaComprobante >= ''%DESDE%''\r\nAND ges_comprobantes.FechaComprobante <= ''%HASTA%''\r\nAND ges_locales.IdLocal like ''%IDTIENDA%''\r\nAND ges_comprobantestipo.TipoComprobante IN (''Factura'',''Boleta'',''Ticket'')', 'TPV', 0, 'Ventas', 0);
;;;;;;
