INSERT INTO `ges_listados` VALUES ('', '(Debug) Log SQL', 'SELECT FechaCreacion as Fecha__FechaHora,TipoProceso as Tipo,Sql as Sentencia__decode64 FROM ges_logsql ORDER BY FechaCreacion DESC, Idlogsql DESC LIMIT 40', 'admin',0,'', 1);
;;;;;;
INSERT INTO `ges_listados` VALUES ('', 'USUARIOS', 'SELECT Nombre, Identificacion, Direccion, Telefono, IF(FechaNacim = ''0000-00-00'','''',DATE_FORMAT(FechaNacim,''%d/%m/%Y'')) AS ''Fecha Nacimiento'', ges_perfiles_usuario.NombrePerfil as Perfil, CuentaBanco as ''Cuenta Bancario'' \r\nFROM ges_usuarios \r\nINNER JOIN ges_perfiles_usuario ON ges_usuarios.IdPerfil = ges_perfiles_usuario.IdPerfil \r\nWHERE ges_usuarios.Eliminado=0 \r\nORDER BY Nombre ASC, Telefono DESC ', 'admin', 0, 'Listas', 0);
;;;;;;

INSERT INTO `ges_listados` VALUES ('', 'IMPORTE DE VENTAS POR PRODUCTOS', 'SELECT CONCAT(ges_productos_idioma.Descripcion,'' '',Marca,'' '',Color,'' '',Talla,'' '',NombreComercial) As Producto, SUM(ges_comprobantesdet.Cantidad) AS Cantidad, ROUND(SUM(ges_comprobantesdet.Importe),2) As Porc__Porcentaje, ROUND(SUM(ges_comprobantesdet.Importe),2) as Importe__Euro FROM ges_comprobantes INNER JOIN ges_comprobantesdet ON ges_comprobantes.IdComprobante = ges_comprobantesdet.IdComprobante INNER JOIN ges_productos ON ges_comprobantesdet.IdProducto = ges_productos.IdProducto INNER JOIN ges_productos_idioma ON ges_productos.IdProdBase = ges_productos_idioma.IdProdBase INNER JOIN ges_marcas ON ges_marcas.IdMarca = ges_productos.IdMarca INNER JOIN ges_laboratorios ON ges_laboratorios.IdLaboratorio = ges_productos.IdLabHab INNER JOIN ges_comprobantesnum ON ges_comprobantes.IdComprobante = ges_comprobantesnum.IdComprobante INNER JOIN ges_comprobantestipo ON ges_comprobantesnum.IdTipoComprobante = ges_comprobantestipo.IdTipoComprobante WHERE  ges_productos_idioma.IdIdioma = ''%IDIDIOMA%'' AND DATE(ges_comprobantes.FechaComprobante) >= ''%DESDE%'' AND DATE(ges_comprobantes.FechaComprobante) <= ''%HASTA%'' AND ges_comprobantes.IdLocal like ''%IDTIENDA%'' AND ges_comprobantestipo.TipoComprobante IN (''Factura'',''Boleta'',''Ticket'') AND ges_productos_idioma.Descripcion like ''%%PRODUCTOIDIOMA%%'' AND ges_comprobantesnum.Status <> ''Anulado'' AND ges_comprobantes.Eliminado = 0 GROUP BY ges_productos.IdProducto ORDER BY Importe__Euro DESC;', 'admin', 0, 'Ventas', 0);
;;;;;;

INSERT INTO `ges_listados` VALUES ('', 'CON STOCK ', 'SELECT  ges_locales.NombreComercial As Local,CodigoBarras As ''Código Barras'',Referencia, Familia, CONCAT(ges_productos_idioma.Descripcion,'' '', Marca,'' '', Color,'' '', Talla,'' '', ges_laboratorios.NombreComercial) As Producto, Unidades, ROUND(CostoUnitario) as Costo , ROUND(PrecioVenta,2) as PVP, ROUND(PrecioVentaCorporativo) as PVC, StockMin, Oferta \r\nFROM ges_almacenes INNER JOIN ges_productos ON ges_almacenes.IdProducto = ges_productos.IdProducto \r\nINNER JOIN ges_locales ON ges_almacenes.IdLocal = ges_locales.IdLocal\r\nINNER JOIN ges_productos_idioma ON ges_productos.IdProdBase = ges_productos_idioma.IdProdBase \r\nINNER JOIN ges_marcas ON ges_marcas.IdMarca = ges_productos.IdMarca \r\nINNER JOIN ges_modelos ON ges_modelos.IdColor = ges_productos.IdColor\r\nINNER JOIN ges_detalles on ges_detalles.IdTalla = ges_productos.IdTalla\r\nINNER JOIN ges_laboratorios ON ges_laboratorios.IdLaboratorio = ges_productos.IdLabHab \r\nINNER JOIN ges_familias ON ges_productos.IdFamilia = ges_familias.IdFamilia\r\nWHERE  ges_almacenes.Unidades > 0\r\nAND ges_almacenes.Eliminado = 0 \r\nAND ges_locales.IdLocal like ''%IDTIENDA%''\r\nAND ges_familias.IdFamilia like ''%IDFAMILIA%''\r\nGROUP BY ges_productos.IdProducto \r\nORDER BY ges_productos_idioma.Descripcion;', 'admin', 0, 'Productos', 0);
;;;;;;

INSERT INTO `ges_listados` VALUES ('', 'OBSOLETOS ', 'SELECT ges_locales.NombreComercial AS Local,CodigoBarras As ''Código Barras'',Referencia, CONCAT(ges_productos_idioma.Descripcion,'' '', Marca,'' '', Color,'' '', Talla,'' '', ges_laboratorios.NombreComercial) As Producto, Unidades, ROUND(PrecioVenta,2) AS PrecioVenta, StockMin, Oferta \r\nFROM ges_almacenes INNER JOIN ges_productos ON ges_almacenes.IdProducto = ges_productos.IdProducto \r\nINNER JOIN ges_locales ON ges_almacenes.IdLocal = ges_locales.IdLocal\r\nINNER JOIN ges_productos_idioma ON ges_productos.IdProdBase = ges_productos_idioma.IdProdBase \r\nINNER JOIN ges_marcas ON ges_marcas.IdMarca = ges_productos.IdMarca \r\nINNER JOIN ges_modelos ON ges_modelos.IdColor = ges_productos.IdColor\r\nINNER JOIN ges_detalles on ges_detalles.IdTalla = ges_productos.IdTalla\r\nINNER JOIN ges_laboratorios ON ges_laboratorios.IdLaboratorio = ges_productos.IdLabHab \r\nWHERE  ges_almacenes.Unidades = 0\r\nAND ges_locales.IdLocal like ''%IDTIENDA%''\r\nAND ges_productos.Obsoleto = 1 \r\nGROUP BY ges_productos.IdProducto \r\nORDER BY ges_productos_idioma.Descripcion;', 'admin', 0, 'Productos', 0);
;;;;;;

INSERT INTO `ges_listados` VALUES ('', 'CON STOCK MINIMO ', 'SELECT  ges_locales.NombreComercial As Local,ges_proveedores.NombreComercial as Proveedor,CodigoBarras As ''Código Barras'',Referencia,CONCAT(ges_productos_idioma.Descripcion,'' '',Marca,'' '',Color,'' '',Talla,'' '',ges_laboratorios.NombreComercial) As Producto, Unidades, ROUND(CostoUnitario) as Costo , ROUND(PrecioVenta,2) as PVP, ROUND(PrecioVentaCorporativo) as PVC, StockMin, Oferta \r\nFROM ges_almacenes INNER JOIN ges_productos ON ges_almacenes.IdProducto=ges_productos.IdProducto \r\nINNER JOIN ges_locales ON ges_almacenes.IdLocal=ges_locales.IdLocal INNER JOIN ges_productos_idioma ON ges_productos.IdProdBase=ges_productos_idioma.IdProdBase INNER JOIN ges_marcas ON ges_marcas.IdMarca=ges_productos.IdMarca INNER JOIN ges_modelos ON ges_modelos.IdColor=ges_productos.IdColor INNER JOIN ges_detalles ON ges_detalles.IdTalla=ges_productos.IdTalla INNER JOIN ges_laboratorios ON ges_laboratorios.IdLaboratorio=ges_productos.IdLabHab INNER JOIN ges_proveedores ON ges_productos.IdProvHab = ges_proveedores.IdProveedor WHERE  ges_almacenes.StockMin>0 AND ges_almacenes.Unidades<=StockMin AND ges_locales.IdLocal like ''%IDTIENDA%'' AND ges_productos.IdProvHab like ''%IDPROVEEDOR%'' AND ges_almacenes.Eliminado=0 GROUP BY ges_productos.IdProducto ORDER BY ges_productos_idioma.Descripcion;', 'admin', 0, 'Productos', 0);
;;;;;;

INSERT INTO `ges_listados` VALUES ('', 'NUEVOS', 'SELECT  ges_locales.NombreComercial As Local, ges_comprobantesprov.TipoComprobante AS Documento, ges_comprobantesprov.Codigo AS ''Nro Doc.'', CodigoBarras AS CB,Referencia AS CR, CONCAT(ges_productos_idioma.Descripcion,'' '', Marca,'' '', Color,'' '', Talla,'' '', ges_laboratorios.NombreComercial) As Producto, ges_proveedores.NombreComercial AS Proveedor, ges_pedidosdet.Unidades,  DATE_FORMAT(ges_pedidos.FechaRecepcion,''%d/%m/%y %k:%i'') AS ''Fecha Compra'', ges_pedidosdet.Lote AS LT,  IF(DATE_FORMAT(ges_pedidosdet.FechaVencimiento,''%e-%b-%Y'') IS NULL,'' '',DATE_FORMAT(ges_pedidosdet.FechaVencimiento,''%d/%m/%y'')) AS FV\r\nFROM ges_pedidosdet INNER JOIN ges_productos ON ges_pedidosdet.IdProducto = ges_productos.IdProducto INNER JOIN ges_pedidos ON ges_pedidosdet.IdPedido = ges_pedidos.IdPedido INNER JOIN ges_locales ON ges_pedidos.IdLocal = ges_locales.IdLocal INNER JOIN ges_productos_idioma ON ges_productos.IdProdBase=ges_productos_idioma.IdProdBase INNER JOIN ges_marcas ON ges_productos.IdMarca = ges_marcas.IdMarca INNER JOIN ges_modelos ON ges_productos.IdColor  = ges_modelos.IdColor INNER JOIN ges_detalles ON ges_productos.IdTalla = ges_detalles.IdTalla INNER JOIN ges_laboratorios ON ges_productos.IdLabHab  = ges_laboratorios.IdLaboratorio INNER JOIN ges_comprobantesprov ON ges_pedidos.IdPedido = ges_comprobantesprov.IdPedido INNER JOIN ges_proveedores ON ges_comprobantesprov.IdProveedor = ges_proveedores.IdProveedor \r\n WHERE  DATE_SUB(CURDATE(),INTERVAL 15 DAY) <= ges_pedidos.FechaRecepcion AND ges_pedidos.IdLocal like ''%IDTIENDA%'' GROUP BY ges_productos.IdProducto HAVING COUNT(ges_pedidosdet.IdProducto)=1 ORDER BY ges_productos_idioma.Descripcion', 'admin', 0, 'Productos', 0);
;;;;;;

INSERT INTO `ges_listados` VALUES ('', 'EN OFERTA', 'SELECT  ges_locales.NombreComercial As Local,CodigoBarras As ''Código Barras'',Referencia,CONCAT(ges_productos_idioma.Descripcion,'' '',Marca,'' '',Color,'' '',Talla,'' '',ges_laboratorios.NombreComercial) As Producto, Unidades, ROUND(PrecioVenta,2) AS PrecioVenta, Oferta, ROUND(PrecioVentaOferta,2) as ''Precio Oferta''\r\nFROM ges_almacenes INNER JOIN ges_productos ON ges_almacenes.IdProducto=ges_productos.IdProducto \r\nINNER JOIN ges_locales ON ges_almacenes.IdLocal=ges_locales.IdLocal INNER JOIN ges_productos_idioma ON ges_productos.IdProdBase=ges_productos_idioma.IdProdBase INNER JOIN ges_marcas ON ges_marcas.IdMarca=ges_productos.IdMarca INNER JOIN ges_modelos ON ges_modelos.IdColor=ges_productos.IdColor INNER JOIN ges_detalles ON ges_detalles.IdTalla=ges_productos.IdTalla INNER JOIN ges_laboratorios ON ges_laboratorios.IdLaboratorio=ges_productos.IdLabHab WHERE  ges_almacenes.Oferta>0 AND ges_almacenes.Unidades>0 AND ges_almacenes.Eliminado=0 AND ges_almacenes.IdLocal like ''%IDTIENDA%'' ORDER BY ges_productos_idioma.Descripcion', 'admin', 0, 'Productos', 0);
;;;;;;


INSERT INTO `ges_listados` VALUES ('', 'EN OFERTA', 'SELECT  ges_locales.NombreComercial As Local,CodigoBarras As ''Código Barras'',Referencia,CONCAT(ges_productos_idioma.Descripcion,'' '',Marca,'' '',Color,'' '',Talla,'' '',ges_laboratorios.NombreComercial) As Producto, Unidades, ROUND(PrecioVenta,2) AS PrecioVenta, Oferta, ROUND(PrecioVentaOferta,2) as ''Precio Oferta''\r\nFROM ges_almacenes INNER JOIN ges_productos ON ges_almacenes.IdProducto=ges_productos.IdProducto \r\nINNER JOIN ges_locales ON ges_almacenes.IdLocal=ges_locales.IdLocal INNER JOIN ges_productos_idioma ON ges_productos.IdProdBase=ges_productos_idioma.IdProdBase INNER JOIN ges_marcas ON ges_marcas.IdMarca=ges_productos.IdMarca INNER JOIN ges_modelos ON ges_modelos.IdColor=ges_productos.IdColor INNER JOIN ges_detalles ON ges_detalles.IdTalla=ges_productos.IdTalla INNER JOIN ges_laboratorios ON ges_laboratorios.IdLaboratorio=ges_productos.IdLabHab WHERE  ges_almacenes.Oferta>0 AND ges_almacenes.Unidades>0 AND ges_almacenes.Eliminado=0 AND ges_almacenes.IdLocal = ''%IDTIENDA%'' ORDER BY ges_productos_idioma.Descripcion', 'TPV', 0, 'Productos', 0);
;;;;;;

INSERT INTO `ges_listados` VALUES ('', 'NUEVOS', 'SELECT ges_locales.NombreComercial As Local, Referencia AS CR, CONCAT(CodigoBarras,'' '',ges_productos_idioma.Descripcion,'' '', Marca,'' '', Color,'' '', Talla,'' '', ges_laboratorios.NombreComercial) As Producto, ges_pedidosdet.Unidades, ges_productos.UnidadMedida as ''UND Medida'', (SELECT ges_almacenes.''%TIPOVENTA%'' FROM ges_almacenes WHERE ges_almacenes.IdProducto = ges_pedidosdet.IdProducto AND ges_almacenes.IdLocal like ''%IDTIENDA%'') as Precio, ges_pedidosdet.Lote, IF(DATE_FORMAT(ges_pedidosdet.FechaVencimiento,''%e-%b-%Y'') IS NULL,'' '',DATE_FORMAT(ges_pedidosdet.FechaVencimiento,''%d/%m/%y'')) AS FV FROM ges_pedidosdet INNER JOIN ges_productos ON ges_pedidosdet.IdProducto = ges_productos.IdProducto INNER JOIN ges_pedidos ON ges_pedidosdet.IdPedido = ges_pedidos.IdPedido INNER JOIN ges_locales ON ges_pedidos.IdLocal = ges_locales.IdLocal INNER JOIN ges_productos_idioma ON ges_productos.IdProdBase=ges_productos_idioma.IdProdBase INNER JOIN ges_marcas ON ges_productos.IdMarca = ges_marcas.IdMarca INNER JOIN ges_modelos ON ges_productos.IdColor = ges_modelos.IdColor INNER JOIN ges_detalles ON ges_productos.IdTalla = ges_detalles.IdTalla INNER JOIN ges_laboratorios ON ges_productos.IdLabHab = ges_laboratorios.IdLaboratorio INNER JOIN ges_comprobantesprov ON ges_pedidos.IdPedido = ges_comprobantesprov.IdPedido INNER JOIN ges_proveedores ON ges_comprobantesprov.IdProveedor = ges_proveedores.IdProveedor WHERE DATE_SUB(CURDATE(),INTERVAL 15 DAY) <= ges_pedidos.FechaRecepcion AND ges_pedidos.IdLocal like ''%IDTIENDA%'' GROUP BY ges_productos.IdProducto HAVING COUNT(ges_pedidosdet.IdProducto)=1 ORDER BY ges_productos_idioma.Descripcion', 'TPV', 0, 'Productos', 0);
;;;;;;

INSERT INTO `ges_listados` VALUES ('', 'INMOVILIZADOS', 'SELECT  ges_locales.NombreComercial As Local,(SELECT ges_comprobantesprov.TipoComprobante FROM ges_comprobantesprov WHERE ges_comprobantesprov.Codigo = ges_comprobantesprov.Codigo AND ges_comprobantesprov.IdMotivoAlbaran = 0) as Documento,ges_comprobantesprov.Codigo, CodigoBarras,Referencia,CONCAT(ges_productos_idioma.Descripcion,'' '',Marca,'' '',Color,'' '',Talla,'' '',ges_laboratorios.NombreComercial) As Producto, ges_pedidosdet.Unidades, ges_pedidosdet.Lote, IF(ges_pedidosdet.FechaVencimiento = ''0000-00-00'','''',(DATE_FORMAT(ges_pedidosdet.FechaVencimiento,''%d/%m/%Y''))) as Vencimiento\r\nFROM ges_pedidosdet \r\nINNER JOIN ges_productos ON ges_pedidosdet.IdProducto=ges_productos.IdProducto \r\nINNER JOIN ges_productos_idioma ON ges_productos.IdProdBase=ges_productos_idioma.IdProdBase \r\nINNER JOIN ges_marcas ON ges_marcas.IdMarca=ges_productos.IdMarca \r\nINNER JOIN ges_modelos ON ges_modelos.IdColor=ges_productos.IdColor \r\nINNER JOIN ges_detalles ON ges_detalles.IdTalla=ges_productos.IdTalla \r\nINNER JOIN ges_laboratorios ON ges_laboratorios.IdLaboratorio=ges_productos.IdLabHab \r\nINNER JOIN ges_pedidos ON ges_pedidosdet.IdPedido = ges_pedidos.IdPedido\r\nINNER JOIN ges_comprobantesprov ON ges_pedidos.IdPedido = ges_comprobantesprov.IdPedido\r\nINNER JOIN ges_motivoalbaran ON ges_comprobantesprov.IdMotivoAlbaran = ges_motivoalbaran.IdMotivoAlbaran\r\nINNER JOIN ges_locales ON ges_pedidos.IdLocal=ges_locales.IdLocal \r\nWHERE  ges_pedidosdet.Eliminado=0  \r\nAND ges_motivoalbaran.MotivoAlbaran = ''Inmovilizacion'' \r\nAND ges_pedidos.IdLocal like ''%IDTIENDA%''\r\nAND ges_comprobantesprov.EstadoDocumento = ''Borrador''\r\nORDER BY ges_comprobantesprov.FechaRegistro ASC', 'admin', 0, 'Productos', 0);
;;;;;;

INSERT INTO `ges_listados` VALUES ('', 'SIN STOCK', 'SELECT  ges_locales.NombreComercial As Local,Referencia as CR,CodigoBarras as CB,CONCAT(ges_productos_idioma.Descripcion,'' '',Marca,'' '',Color,'' '',Talla,'' '',ges_laboratorios.NombreComercial) As Producto, Unidades, ROUND(CostoUnitario) as Costo , ROUND(PrecioVenta,2) as PVP, ROUND(PrecioVentaCorporativo) as PVC, StockMin\r\nFROM ges_almacenes \r\nINNER JOIN ges_productos ON ges_almacenes.IdProducto=ges_productos.IdProducto \r\nINNER JOIN ges_locales ON ges_almacenes.IdLocal=ges_locales.IdLocal \r\nINNER JOIN ges_productos_idioma ON ges_productos.IdProdBase=ges_productos_idioma.IdProdBase \r\nINNER JOIN ges_marcas ON ges_marcas.IdMarca=ges_productos.IdMarca \r\nINNER JOIN ges_modelos ON ges_modelos.IdColor=ges_productos.IdColor \r\nINNER JOIN ges_detalles ON ges_detalles.IdTalla=ges_productos.IdTalla \r\nINNER JOIN ges_laboratorios ON ges_laboratorios.IdLaboratorio=ges_productos.IdLabHab \r\nWHERE  ges_almacenes.Unidades=0  AND ges_almacenes.Eliminado=0\r\nAND ges_locales.IdLocal like ''%IDTIENDA%'' \r\nGROUP BY ges_productos.IdProducto \r\nORDER BY ges_locales.IdLocal,ges_productos_idioma.Descripcion', 'admin', 0, 'Productos', 0);
;;;;;;

INSERT INTO `ges_listados` VALUES ('', 'POR USUARIO', 'SELECT ges_locales.NombreComercial as Local, ges_usuarios.Nombre as Usuario, COUNT(ges_comprobantes.IdUsuario) as Cantidad, ROUND(SUM(ges_comprobantes.TotalImporte),2) as ''Importe %SML%'' \r\nFROM ges_comprobantes \r\nINNER JOIN ges_usuarios ON ges_comprobantes.IdUsuario = ges_usuarios.IdUsuario \r\nINNER JOIN ges_locales ON ges_locales.IdLocal = ges_comprobantes.IdLocal\r\nINNER JOIN ges_comprobantesnum ON ges_comprobantes.IdComprobante = ges_comprobantesnum.IdComprobante\r\nINNER JOIN ges_comprobantestipo ON ges_comprobantesnum.IdTipoComprobante = ges_comprobantestipo.IdTipoComprobante\r\nWHERE ges_comprobantes.Eliminado = 0\r\nAND ges_comprobantestipo.TipoComprobante <> ''AlbaranInt''\r\nAND ges_comprobantesnum.Status <> ''Anulado'' \r\nAND DATE(ges_comprobantes.FechaComprobante) >= ''%DESDE%''\r\nAND DATE(ges_comprobantes.FechaComprobante) <= ''%HASTA%''\r\nAND ges_comprobantes.IdLocal like ''%IDTIENDA%''\r\nGROUP BY ges_comprobantes.IdUsuario\r\nORDER BY ''Importe %SML%'' DESC', 'admin', 0, 'Ventas', 0);
;;;;;;

INSERT INTO `ges_listados` VALUES ('', 'CLIENTES FRECUENTES', 'SELECT ges_locales.NombreComercial as Local, ges_clientes.TipoCliente as ''Tipo Cliente'', IF(ges_clientes.TipoCliente = ''Empresa'',ges_clientes.NombreLegal,ges_clientes.NombreComercial) as CLiente, ges_clientes.NumeroFiscal as ''DNI/RUC'', COUNT(ges_comprobantes.IdCliente) as Cantidad, \r\nROUND(SUM(ges_comprobantes.TotalImporte),2) as ''Importe %SML%''\r\nFROM ges_comprobantes\r\nINNER JOIN ges_clientes ON ges_comprobantes.IdCliente = ges_clientes.IdCliente \r\nINNER JOIN ges_locales ON ges_comprobantes.IdLocal = ges_locales.IdLocal\r\nINNER JOIN ges_comprobantesnum ON ges_comprobantes.IdComprobante = ges_comprobantesnum.IdComprobante\r\nINNER JOIN ges_comprobantestipo ON ges_comprobantesnum.IdTipoComprobante = ges_comprobantestipo.IdTipoComprobante\r\nWHERE ges_comprobantes.Eliminado = 0\r\nAND ges_comprobantestipo.TipoComprobante <> ''AlbaranInt''\r\nAND ges_comprobantestipo.TipoComprobante <> ''Albaran''\r\n AND ges_comprobantesnum.Status <> ''Anulado''\r\n AND DATE(ges_comprobantes.FechaComprobante) >= ''%DESDE%''\r\nAND DATE(ges_comprobantes.FechaComprobante) <= ''%HASTA%''\r\nAND ges_comprobantes.IdLocal like ''%IDTIENDA%''\r\nAND ges_clientes.TipoCliente like ''%TIPOCLIENTE%''\r\nGROUP BY ges_locales.IdLocal,ges_comprobantes.IdCliente\r\nORDER BY ges_locales.IdLocal ASC,ges_clientes.TipoCliente ASC,Cantidad DESC', 'admin', 0, 'Ventas', 0);
;;;;;;

INSERT INTO `ges_listados` VALUES ('', 'CLIENTES FRECUENTES', 'SELECT ges_locales.NombreComercial as Local, ges_clientes.TipoCliente as ''Tipo Cliente'', IF(ges_clientes.TipoCliente = ''Empresa'',ges_clientes.NombreLegal,ges_clientes.NombreComercial) as CLiente, ges_clientes.NumeroFiscal as ''DNI/RUC'', COUNT(ges_comprobantes.IdCliente) as Cantidad, \r\nROUND(SUM(ges_comprobantes.TotalImporte),2) as ''Importe %SML%''\r\nFROM ges_comprobantes\r\nINNER JOIN ges_clientes ON ges_comprobantes.IdCliente = ges_clientes.IdCliente \r\nINNER JOIN ges_locales ON ges_comprobantes.IdLocal = ges_locales.IdLocal\r\nINNER JOIN ges_comprobantesnum ON ges_comprobantes.IdComprobante = ges_comprobantesnum.IdComprobante\r\nINNER JOIN ges_comprobantestipo ON ges_comprobantesnum.IdTipoComprobante = ges_comprobantestipo.IdTipoComprobante\r\nWHERE ges_comprobantes.Eliminado = 0\r\nAND ges_comprobantestipo.TipoComprobante <> ''AlbaranInt''\r\nAND ges_comprobantestipo.TipoComprobante <> ''Albaran''\r\n AND ges_comprobantesnum.Status <> ''Anulado''\r\nAND DATE(ges_comprobantes.FechaComprobante) >= ''%DESDE%''\r\nAND DATE(ges_comprobantes.FechaComprobante) <= ''%HASTA%''\r\nAND ges_comprobantes.IdLocal = ''%IDTIENDA%''\r\nAND ges_clientes.TipoCliente like ''%TIPOCLIENTE%''\r\nGROUP BY ges_comprobantes.IdCliente\r\nORDER BY ges_clientes.TipoCliente ASC,Cantidad DESC', 'TPV', 0, 'Ventas', 0);
;;;;;;

INSERT INTO `ges_listados` VALUES ('', 'N/S PRODUCTO - COMPRAS', 'SELECT ges_locales.NombreComercial as Almacén,ges_comprobantesprov.TipoComprobante as Comprobante, ges_comprobantesprov.Codigo as ''Serie-Nro'', DATE_FORMAT(ges_comprobantesprov.FechaFacturacion,''%d/%m/%Y %H:%i'') as ''Fecha Emisión'',ges_proveedores.NombreLegal  as Proveedor\r\n,CodigoBarras AS CB,Referencia AS CR, CONCAT(ges_productos_idioma.Descripcion,'' '', Marca,'' '', Color,'' '', Talla,'' '', ges_laboratorios.NombreLegal) As Producto, NumeroSerie as ''Número Serie'' \r\nFROM ges_productos_series \r\nINNER JOIN ges_productos ON ges_productos_series.IdProducto = ges_productos.IdProducto \r\nINNER JOIN ges_productos_idioma ON ges_productos.IdProdBase = ges_productos_idioma.IdProdBase \r\nINNER JOIN ges_marcas ON ges_productos.IdMarca = ges_marcas.IdMarca \r\nINNER JOIN ges_modelos ON ges_productos.IdColor = ges_modelos.IdColor \r\nINNER JOIN ges_detalles ON ges_productos.IdTalla = ges_detalles.IdTalla \r\nINNER JOIN ges_laboratorios ON ges_productos.IdLabHab = ges_laboratorios.IdLaboratorio \r\nINNER JOIN ges_pedidosdet ON ges_productos_series.DocumentoEntrada = ges_pedidosdet.IdPedidoDet \r\nINNER JOIN ges_pedidos ON ges_pedidosdet.IdPedido = ges_pedidos.IdPedido \r\nINNER JOIN ges_comprobantesprov ON ges_pedidos.IdPedido = ges_comprobantesprov.IdPedido\r\nINNER JOIN ges_proveedores ON ges_comprobantesprov.IdProveedor = ges_proveedores.IdProveedor\r\nINNER JOIN ges_locales ON ges_pedidos.IdLocal = ges_locales.Idlocal \r\nWHERE ges_productos_series.Eliminado = 0 \r\nAND ges_productos_series.OperacionEntrada <> ''MetaProducto''\r\nAND ges_productos_series.NumeroSerie like ''%%NUMEROSERIE%%''', 'admin', 0, 'Busquedas', 0);
;;;;;;

INSERT INTO `ges_listados` VALUES ('', 'N/S PRODUCTO - VENTAS', 'SELECT ges_locales.NombreComercial as Almacén,ges_comprobantestipo.TipoComprobante as Comprobante, CONCAT(ges_comprobantestipo.Serie,'' - '',ges_comprobantesnum.NumeroComprobante) as ''Serie-Nro'', DATE_FORMAT(ges_comprobantesnum.Fecha,''%d/%m/%Y %H:%i'') as ''Fecha Emisión'',IF(ges_clientes.TipoCliente = ''Empresa'',ges_clientes.NombreLegal,ges_clientes.NombreComercial) as CLiente \r\n,ges_productos.CodigoBarras AS CB,ges_productos.Referencia AS CR, CONCAT(ges_productos_idioma.Descripcion,'' '', Marca,'' '', ges_modelos.Color,'' '', ges_detalles.Talla,'' '', ges_laboratorios.NombreLegal) As Producto, NumeroSerie as ''Número Serie'' \r\nFROM ges_productos_series \r\nINNER JOIN ges_productos ON ges_productos_series.IdProducto = ges_productos.IdProducto \r\nINNER JOIN ges_productos_idioma ON ges_productos.IdProdBase = ges_productos_idioma.IdProdBase \r\nINNER JOIN ges_marcas ON ges_productos.IdMarca = ges_marcas.IdMarca \r\nINNER JOIN ges_modelos ON ges_productos.IdColor = ges_modelos.IdColor \r\nINNER JOIN ges_detalles ON ges_productos.IdTalla = ges_detalles.IdTalla \r\nINNER JOIN ges_laboratorios ON ges_productos.IdLabHab = ges_laboratorios.IdLaboratorio\r\nINNER JOIN ges_comprobantes ON ges_productos_series.DocumentoSalida = ges_comprobantes.IdComprobante\r\nINNER JOIN ges_comprobantesdet ON ges_comprobantes.IdComprobante = ges_comprobantesdet.IdComprobante\r\nINNER JOIN ges_comprobantesnum  ON ges_comprobantes.IdComprobante = ges_comprobantesnum.IdComprobante\r\nINNER JOIN ges_comprobantestipo ON ges_comprobantesnum.IdTipoComprobante = ges_comprobantestipo.IdTipoComprobante\r\nINNER JOIN ges_clientes ON ges_comprobantes.IdCliente = ges_clientes.IdCliente\r\nINNER JOIN ges_locales ON ges_comprobantes.IdLocal = ges_locales.Idlocal\r\nWHERE ges_productos_series.Eliminado = 0 \r\nAND ges_productos_series.OperacionSalida <> ''MetaProducto''\r\nAND ges_productos_series.DocumentoEntrada = ges_comprobantesdet.IdPedidoDet \r\nAND ges_productos_series.NumeroSerie like ''%%NUMEROSERIE%%''', 'admin', 0, 'Busquedas', 0);
;;;;;;

INSERT INTO `ges_listados` VALUES ('', 'LOTE PRODUCCION - COMPRAS', 'SELECT ges_locales.NombreComercial as Almacén,ges_comprobantesprov.TipoComprobante as Comprobante, ges_comprobantesprov.Codigo as ''Serie-Nro'', DATE_FORMAT(ges_comprobantesprov.FechaFacturacion,''%d/%m/%Y %H:%i'') as ''Fecha Emisión'',ges_proveedores.NombreLegal  as Proveedor\r\n,CodigoBarras AS CB,Referencia AS CR, CONCAT(ges_productos_idioma.Descripcion,'' '', Marca,'' '', Color,'' '', Talla,'' '', ges_laboratorios.NombreLegal) As Producto, ges_pedidosdet.Lote \r\nFROM ges_pedidosdet \r\nINNER JOIN ges_pedidos ON ges_pedidosdet.IdPedido = ges_pedidos.IdPedido \r\nINNER JOIN ges_locales ON ges_pedidos.IdLocal = ges_locales.Idlocal \r\nINNER JOIN ges_productos ON ges_pedidosdet.IdProducto = ges_productos.IdProducto \r\nINNER JOIN ges_productos_idioma ON ges_productos.IdProdBase = ges_productos_idioma.IdProdBase \r\nINNER JOIN ges_marcas ON ges_productos.IdMarca = ges_marcas.IdMarca \r\nINNER JOIN ges_modelos ON ges_productos.IdColor = ges_modelos.IdColor \r\nINNER JOIN ges_detalles ON ges_productos.IdTalla = ges_detalles.IdTalla \r\nINNER JOIN ges_laboratorios ON ges_productos.IdLabHab = ges_laboratorios.IdLaboratorio \r\nINNER JOIN ges_comprobantesprov ON ges_pedidos.IdPedido = ges_comprobantesprov.IdPedido\r\nINNER JOIN ges_proveedores ON ges_comprobantesprov.IdProveedor = ges_proveedores.IdProveedor\r\n\r\nWHERE ges_pedidosdet.Eliminado = 0 \r\nAND ges_productos.Lote = 1\r\nAND ges_pedidosdet.Lote like ''%%LOTE%%''', 'admin', 0, 'Busquedas', 0);
;;;;;;

INSERT INTO `ges_listados` VALUES ('', 'PARTIDAS DE CAJA', 'SELECT TipoCaja as ''Tipo Caja'', TipoOperacion as Operación, PartidaCaja as ''Partidas'', DATE_FORMAT(FechaRegistro,''%d/%m/%Y'') as ''Fecha Registro'' FROM ges_partidascaja WHERE FechaRegistro >=''%DESDE%'' AND FechaRegistro<=''%HASTA%'' \r\nOR (IdLocal = 0 OR IdLocal like ''%IDTIENDA%'') AND Eliminado = 0 ORDER BY TipoCaja ASC, PartidaCaja ASC', 'admin', 0, 'Listas', 0);
;;;;;;

INSERT INTO `ges_listados` VALUES ('', 'MOVIMIENTOS DE PARTIDAS CAJA GENERAL', 'SELECT ges_usuarios.Identificacion as Usuario,DATE_FORMAT(FechaInsercion,''%d/%m/%Y %H:%s'') as ''Fecha Operación'', PartidaCaja as ''Partida Caja'',ges_librodiario_cajagral.TipoOperacion as Operación,Concepto, CONCAT(Documento,'' '',CodigoDocumento,'' '',(IF(ges_librodiario_cajagral.IdSubsidiario <> 0,(SELECT NombreLegal FROM ges_subsidiarios WHERE ges_subsidiarios.IdSubsidiario = ges_librodiario_cajagral.IdSubsidiario),''''))) AS Documento, IF(ges_librodiario_cajagral.IdMoneda = 1," ",ges_librodiario_cajagral.CambioMoneda)  as ''Cambio Moneda'',Simbolo as Moneda, ROUND(ges_librodiario_cajagral.Importe,2) as Importe\r\nFROM ges_librodiario_cajagral \r\nINNER JOIN ges_partidascaja ON ges_librodiario_cajagral.IdPartidaCaja = ges_partidascaja.IdPartidaCaja\r\nINNER JOIN ges_moneda ON ges_librodiario_cajagral.IdMoneda = ges_moneda.IdMoneda\r\nINNER JOIN ges_usuarios ON ges_librodiario_cajagral.IdUsuario = ges_usuarios.IdUsuario\r\nWHERE ges_librodiario_cajagral.Eliminado = 0\r\nAND ges_librodiario_cajagral.IdPartidaCaja like ''%PARTIDA%''\r\nAND ges_librodiario_cajagral.IdLocal like ''%IDTIENDA%''\r\nAND DATE(FechaInsercion) >= ''%DESDE%'' \r\nAND DATE(FechaInsercion) <= ''%HASTA%''', 'admin', 0, 'Finanzas', 0);
;;;;;;

INSERT INTO `ges_listados` VALUES ('', 'CONSOLIDADO DE PARTIDAS CAJA GENERAL', 'SELECT PartidaCaja as ''Partida'', ROUND(SUM(CambioMoneda*Importe),2) AS ''Importe %SML%''\r\nFROM ges_librodiario_cajagral\r\nINNER JOIN ges_partidascaja ON ges_librodiario_cajagral.IdPartidaCaja = ges_partidascaja.IdPartidaCaja\r\nWHERE ges_librodiario_cajagral.Eliminado = 0 \r\nAND DATE(ges_librodiario_cajagral.FechaInsercion) >= ''%DESDE%'' \r\nAND DATE(ges_librodiario_cajagral.FechaInsercion) <= ''%HASTA%''\r\nAND ges_librodiario_cajagral.IdLocal like ''%IDTIENDA%'' \r\nGROUP BY ges_librodiario_cajagral.IdPartidaCaja', 'admin', 0, 'Finanzas', 0);
;;;;;;

INSERT INTO `ges_listados` VALUES ('', 'MOVIMIENTOS DE CAJA TPV', 'SELECT ges_locales.NombreComercial as Local,DATE_FORMAT(ges_arqueo_caja.FechaApertura,''%d/%m/%y'') as ''Arqueo Apertura'', DATE_FORMAT(ges_arqueo_caja.FechaCierre,''%d/%m/%y'') as ''Arqueo Cierre'',ges_usuarios.Identificacion AS Usuario,IF(IdPartidaCaja = 0,''Ventas'',(SELECT PartidaCaja FROM ges_partidascaja WHERE ges_partidascaja.IdPartidaCaja = ges_dinero_movimientos.IdPartidaCaja)) AS ''Partida'', DATE_FORMAT(FechaPago,''%d/%m/%y %H:%s'') as ''Fecha Operación'', ges_dinero_movimientos.TipoOperacion AS Operación, ges_modalidadespago.ModalidadPago as ''Modalidad Pago'', IF(ges_dinero_movimientos.IdComprobante = 0,'''' '''',(SELECT ges_clientes.NombreComercial \r\nFROM ges_clientes INNER JOIN ges_comprobantes ON ges_clientes.IdCliente = ges_comprobantes.IdCliente WHERE ges_comprobantes.IdComprobante = ges_dinero_movimientos.IdComprobante)) as Cliente ,Concepto, ROUND(Importe,2) AS ''Importe %SML%'' \r\nFROM ges_dinero_movimientos \r\nINNER JOIN ges_usuarios ON ges_dinero_movimientos.IdUsuario = ges_usuarios.IdUsuario \r\nINNER JOIN ges_locales ON ges_dinero_movimientos.IdLocal = ges_locales.IdLocal \r\nINNER JOIN ges_arqueo_caja ON ges_dinero_movimientos.IdArqueoCaja = ges_arqueo_caja.IdArqueo \r\nINNER JOIN ges_modalidadespago ON ges_dinero_movimientos.IdModalidadPago = ges_modalidadespago.IdModalidadPago\r\nWHERE ges_dinero_movimientos.Eliminado = 0 \r\nAND ges_dinero_movimientos.TipoVentaOperacion like ''%TIPOVENTAOP%'' \r\nAND DATE(FechaPago) >= ''%DESDE%'' \r\nAND DATE(FechaPago) <= ''%HASTA%''\r\nAND ges_dinero_movimientos.IdLocal like ''%IDTIENDA%''\r\nAND ges_dinero_movimientos.Importe > 0\r\nAND ges_dinero_movimientos.TipoOperacion like ''%TIPOOPERACION%''\r\nAND ges_dinero_movimientos.IdModalidadPago like ''%MODALIDADPAGO%''\r\nORDER BY ges_arqueo_caja.FechaApertura ASC,ges_dinero_movimientos.TipoOperacion ASC, Partida ASC', 'admin', 0, 'Finanzas', 0);
;;;;;;

INSERT INTO `ges_listados` VALUES ('', 'PARTIDAS', 'SELECT PartidaCaja as Partidas, TipoOperacion as Operación, DATE_FORMAT(FechaRegistro,''%d/%m/%Y %H:%s'') as ''Fecha Registro''\r\nFROM ges_partidascaja\r\nWHERE Eliminado = 0 \r\nAND TipoCaja = ''%TIPOVENTAOP%'' \r\nAND IdLocal IN (0,''%IDLOCAL%'')\r\nORDER BY PartidaCaja ASC', 'TPV', 0, 'Listas', 0);
;;;;;;

INSERT INTO `ges_listados` VALUES ('', 'TRASLADOS', 'SELECT DATE_FORMAT(ges_comprobantes.FechaComprobante,''%d/%m/%Y %H:%i'') AS Fecha,CONCAT(ges_productos_idioma.Descripcion,'' '',Marca,'' '',Color,'' '',Talla,'' '',ges_laboratorios.NombreComercial) As Producto, ges_locales.NombreComercial as Local, (SELECT ges_locales.nombreComercial FROM ges_locales WHERE ges_locales.IdLocal = ges_comprobantes.IdCliente) AS Destinatario, ges_comprobantesdet.Cantidad, ROUND(ges_comprobantesdet.CostoUnitario,2) as Costo, ROUND((ges_comprobantesdet.CostoUnitario*ges_comprobantesdet.cantidad),2) as Importe \r\nFROM ges_comprobantes \r\nINNER JOIN ges_comprobantesdet ON ges_comprobantes.IdComprobante = ges_comprobantesdet.IdComprobante \r\nINNER JOIN ges_productos ON ges_comprobantesdet.IdProducto = ges_productos.IdProducto \r\nINNER JOIN ges_productos_idioma ON ges_productos.IdProdBase = ges_productos_idioma.IdProdBase \r\nINNER JOIN ges_marcas ON ges_marcas.IdMarca = ges_productos.IdMarca \r\nINNER JOIN ges_laboratorios ON ges_laboratorios.IdLaboratorio = ges_productos.IdLabHab \r\nINNER JOIN ges_comprobantesnum ON ges_comprobantes.IdComprobante = ges_comprobantesnum.IdComprobante \r\nINNER JOIN ges_comprobantestipo ON ges_comprobantesnum.IdTipoComprobante = ges_comprobantestipo.IdTipoComprobante\r\nINNER JOIN ges_motivoalbaran ON ges_comprobantesnum.IdMotivoAlbaran = ges_motivoalbaran.IdMotivoAlbaran\r\nINNER JOIN ges_locales ON ges_comprobantes.IdLocal = ges_locales.IdLocal\r\nWHERE DATE(ges_comprobantes.FechaComprobante) >= ''%DESDE%'' \r\nAND DATE(ges_comprobantes.FechaComprobante) <= ''%HASTA%'' \r\nAND ges_comprobantes.IdLocal like ''%IDTIENDA%'' \r\nAND ges_comprobantestipo.TipoComprobante IN (''AlbaranInt'') \r\nAND ges_comprobantes.Destinatario = ''Local''\r\nAND ges_motivoalbaran.MotivoAlbaran = ''Traslado''\r\nAND ges_comprobantes.Eliminado = 0 \r\nORDER BY ges_comprobantes.IdLocal;', 'admin', 0, 'Productos', 0);
;;;;;;

INSERT INTO `ges_listados` VALUES ('', 'COMPROBANTES', 'SELECT ges_locales.NombreComercial as Local, DATE_FORMAT(ges_comprobantesprov.FechaFacturacion,''%d/%m/%Y'') as ''Fecha Emisión'',ges_proveedores.NombreComercial as Proveedor, ges_comprobantesprov.Codigo as ''Serie-Nro'', ges_comprobantesprov.TipoComprobante as Comprobante, ges_comprobantesprov.EstadoPago as ''Estado Pago'', ges_moneda.Simbolo as Moneda,ROUND(ges_comprobantesprov.TotalImporte,2) as Importe, ROUND(ges_comprobantesprov.ImporteImpuesto,2) as Impuesto, ROUND(ges_comprobantesprov.ImportePercepcion,2) as Percepción, ROUND(ges_comprobantesprov.ImporteFlete,2) as Flete, ROUND(ges_comprobantesprov.ImportePago,2) as ''Importe Pago'', ROUND(ges_comprobantesprov.ImportePendiente,2) as Pendiente \r\nFROM ges_comprobantesprov \r\nINNER JOIN ges_pedidos ON ges_comprobantesprov.IdPedido =  ges_pedidos.IdPedido\r\nINNER JOIN ges_locales ON ges_pedidos.IdLocal = ges_locales.IdLocal\r\nINNER JOIN ges_moneda ON ges_pedidos.IdMoneda = ges_moneda.IdMoneda\r\nINNER JOIN ges_proveedores ON ges_comprobantesprov.IdProveedor = ges_proveedores.IdProveedor\r\nWHERE ges_comprobantesprov.Eliminado = 0\r\nAND ges_comprobantesprov.TipoComprobante <> ''AlbaranInt'' \r\nAND ges_comprobantesprov.EstadoPago <> ''Exonerado'' \r\nAND ges_comprobantesprov.FechaFacturacion >= ''%DESDE%''\r\nAND ges_comprobantesprov.FechaFacturacion <= ''%HASTA%''\r\nAND ges_pedidos.IdLocal like ''%IDTIENDA%''\r\nAND ges_comprobantesprov.IdProveedor like ''%IDPROVEEDOR%''\r\nAND ges_comprobantesprov.TipoComprobante like ''%TIPOCOMPROBANTE%''\r\nAND ges_comprobantesprov.EstadoDocumento like ''%ESTADOCOMPROBANTE%''\r\nAND ges_comprobantesprov.EstadoPago like ''%ESTADOPAGO%''\r\nORDER BY ges_comprobantesprov.TipoComprobante ASC, ges_comprobantesprov.EstadoPago ASC', 'admin', 0, 'Compras', 0);
;;;;;;

INSERT INTO `ges_listados` VALUES ('', 'COMPROBANTES', 'SELECT ges_locales.NombreComercial as Local, DATE_FORMAT(ges_comprobantes.FechaComprobante,''%d/%m/%y %H:%i'') as ''Fecha Emisión'',IF(ges_clientes.TipoCliente = ''Empresa'',ges_clientes.NombreLegal,ges_clientes.NombreComercial) as Cliente, CONCAT(ges_comprobantes.SerieComprobante,''-'',ges_comprobantes.NComprobante) as Código,CONCAT(ges_comprobantestipo.Serie,'' - '',ges_comprobantesnum.NumeroComprobante) as ''Serie-Nro'', ges_comprobantestipo.TipoComprobante as Comprobante, ges_comprobantesnum.Status as ''Estado'', ROUND(ges_comprobantes.TotalImporte,2) as Importe, ROUND(ges_comprobantes.ImporteImpuesto,2) as Impuesto,  ROUND(ges_comprobantes.ImportePendiente,2) as Pendiente \r\nFROM ges_comprobantes\r\nINNER JOIN ges_locales ON ges_comprobantes.IdLocal = ges_locales.IdLocal\r\nINNER JOIN ges_comprobantesnum ON ges_comprobantes.IdComprobante =  ges_comprobantesnum.IdComprobante\r\nINNER JOIN ges_comprobantestipo ON ges_comprobantesnum.IdTipoComprobante = ges_comprobantestipo.IdTipoComprobante \r\nINNER JOIN ges_clientes ON ges_comprobantes.IdCliente = ges_clientes.IdCliente \r\nWHERE ges_comprobantes.Eliminado = 0\r\nAND ges_comprobantestipo.TipoComprobante IN (''Factura'',''Boleta'',''Ticket'',''Albaran'')\r\nAND DATE(ges_comprobantes.FechaComprobante) >= ''%DESDE%''\r\nAND DATE(ges_comprobantes.FechaComprobante) <= ''%HASTA%''\r\nAND ges_comprobantes.IdLocal  like ''%IDTIENDA%''\r\nAND ges_comprobantestipo.Serie like ''%%SERIECOMPROBANTE%%'' \r\nAND ges_comprobantestipo.TipoComprobante like ''%TIPOCOMPROBANTE%''\r\n''%TIPOVENTATPV%''\r\n''%VENTAESTADO%''\r\nORDER BY ges_comprobantestipo.TipoComprobante ASC,ges_comprobantesnum.Status ASC,ges_comprobantes.ImportePendiente ASC', 'admin', 0, 'Ventas', 0);
;;;;;;

INSERT INTO `ges_listados` VALUES ('', 'PRODUCTOS ANOTADOS', 'SELECT ges_locales.NombreComercial as Local, DATE_FORMAT(ges_productosborrador.FechaRegistro,''%d/%m/%Y %H:%i'') as ''Fecha Registro'', ProductoBorrador as Producto, ges_usuarios.Identificacion as Usuario \r\nFROM ges_productosborrador\r\nINNER JOIN ges_locales ON ges_productosborrador.IdLocal = ges_locales.IdLocal\r\nINNER JOIN ges_usuarios ON ges_productosborrador.IdUsuario = ges_usuarios.IdUsuario\r\nWHERE DATE(ges_productosborrador.FechaRegistro) >= ''%DESDE%''\r\nAND DATE(ges_productosborrador.FechaRegistro) <= ''%HASTA%''\r\nAND ges_productosborrador.IdLocal like ''%IDTIENDA%''\r\nAND ges_productosborrador.Eliminado = 0\r\nORDER BY Producto ASC', 'admin', 0, 'Listas', 0);
;;;;;;

INSERT INTO `ges_listados` VALUES ('', 'PRODUCTOS ANOTADOS', 'SELECT ges_locales.NombreComercial as Local, DATE_FORMAT(ges_productosborrador.FechaRegistro,''%d/%m/%Y %H:%i'') as ''Fecha Registro'', ProductoBorrador as Producto, ges_usuarios.Identificacion as Usuario \r\nFROM ges_productosborrador\r\nINNER JOIN ges_locales ON ges_productosborrador.IdLocal = ges_locales.IdLocal\r\nINNER JOIN ges_usuarios ON ges_productosborrador.IdUsuario = ges_usuarios.IdUsuario\r\nWHERE DATE(ges_productosborrador.FechaRegistro) >= ''%DESDE%''\r\nAND DATE(ges_productosborrador.FechaRegistro) <= ''%HASTA%''\r\nAND ges_productosborrador.IdLocal = ''%IDTIENDA%''\r\nAND ges_productosborrador.Eliminado = 0\r\nORDER BY Producto ASC', 'TPV', 0, 'Listas', 0);
;;;;;;

INSERT INTO `ges_listados` VALUES ('', 'PROMOCIONES', 'SELECT ges_locales.NombreComercial as Local, DATE_FORMAT(ges_promociones.FechaRegistro,''%d/%m/%Y %H:%i'') as ''Fecha Registro'', ges_promociones.Descripcion, DATE_FORMAT(FechaInicio,''%d/%m/%Y %H:%i'') as ''Fecha Inicio'',DATE_FORMAT(FechaFin,''%d/%m/%Y %H:%i'') as ''Fecha Fin'', ges_promociones.Estado, IF(ges_promociones.Modalidad = ''MontoCompra'',''Monto Compra'',''Historial Compra'') as Modalidad, MontoCompraActual as ''Monto Compra'', ges_promociones.Tipo, IF(CBProducto0 = 0,'''',CBProducto0 ) as ''CB Producto'', IF(CBProducto1 = 0,'''',CBProducto1) as ''CB Producto Alternativa'', IF(ges_promociones.Descuento = 0,'''',ges_promociones.Descuento) as ''Descuento(%)'', IF(Bono = 0,'''',Bono) as Bono\r\nFROM ges_promociones\r\nINNER JOIN ges_locales ON ges_promociones.IdLocal = ges_locales.IdLocal\r\nWHERE ges_promociones.Eliminado = 0\r\nAND DATE(ges_promociones.FechaRegistro) >= ''%DESDE%''\r\nAND DATE(ges_promociones.FechaRegistro) <= ''%HASTA%''\r\nAND ges_promociones.IdLocal  like ''%IDTIENDA%''\r\nAND ges_promociones.Modalidad like ''%MODALIDAD%'' \r\nAND ges_promociones.Estado like ''%ESTADOPROMO%''\r\nAND ges_promociones.Tipo like ''%TIPOPROMO%''', 'admin', 0, 'Promociones', 0);
;;;;;;

INSERT INTO `ges_listados` VALUES ('', 'PROMOCIONES', 'SELECT ges_locales.NombreComercial as Local, DATE_FORMAT(ges_promociones.FechaRegistro,''%d/%m/%Y %H:%i'') as ''Fecha Registro'', ges_promociones.Descripcion, DATE_FORMAT(FechaInicio,''%d/%m/%Y %H:%i'') as ''Fecha Inicio'',DATE_FORMAT(FechaFin,''%d/%m/%Y %H:%i'') as ''Fecha Fin'', ges_promociones.Estado, IF(ges_promociones.Modalidad = ''MontoCompra'',''Monto Compra'',''Historial Compra'') as Modalidad, MontoCompraActual as ''Monto Compra'', ges_promociones.Tipo, IF(CBProducto0 = 0,'''',CBProducto0 ) as ''CB Producto'', IF(CBProducto1 = 0,'''',CBProducto1) as ''CB Producto Alternativa'', IF(ges_promociones.Descuento = 0,'''',ges_promociones.Descuento) as ''Descuento(%)'', IF(Bono = 0,'''',Bono) as Bono\r\nFROM ges_promociones\r\nINNER JOIN ges_locales ON ges_promociones.IdLocal = ges_locales.IdLocal\r\nWHERE ges_promociones.Eliminado = 0\r\nAND DATE(ges_promociones.FechaRegistro) >= ''%DESDE%''\r\nAND DATE(ges_promociones.FechaRegistro) <= ''%HASTA%''\r\nAND ges_promociones.IdLocal  = ''%IDTIENDA%''\r\nAND ges_promociones.Modalidad like ''%MODALIDAD%'' \r\nAND ges_promociones.Estado = ''Ejecucion''\r\nAND ges_promociones.Tipo like ''%TIPOPROMO%''', 'TPV', 0, 'Promociones', 0);
;;;;;;

INSERT INTO `ges_listados` VALUES ('', 'ARQUEO CAJA TPV', 'SELECT ges_locales.NombreComercial as Local, IF(TipoVentaOperacion=''VD'',''B2C'',''B2B'') as ''Tipo Venta'', DATE_FORMAT(FechaCierre,''%d/%m/%Y %H:%i'') AS ''Fecha Cierre'', ROUND(ImporteApertura,2) as ''Importe Apertura'', ROUND(ImporteIngresos,2) as ''Importe Ingreso'', ROUND(ImporteGastos,2) as ''Importe Gastos'', ROUND(ImporteAportaciones,2) as ''Importe Aportacion'', ROUND(ImporteSustracciones,2) as ''Importe Sustraccion'', ROUND(ImporteTeoricoCierre,2) as ''Importe Teorico Cierre'', ROUND(ImporteCierre,2) as ''Importe Cierre'',  ROUND(ImporteDescuadre,2) as ''Importe Descuadre'', ROUND(UtilidadVenta,2) as ''Utilidad Venta''  FROM ges_arqueo_caja  INNER JOIN ges_locales ON ges_arqueo_caja.IdLocal = ges_locales.IdLocal \r\nWHERE ges_arqueo_caja.Eliminado = 0 AND TipoVentaOperacion like ''%TIPOVENTAOP%'' AND ges_arqueo_caja.IdLocal like ''%IDTIENDA%'' AND DATE(FechaCierre) >= ''%DESDE%'' AND DATE(FechaCierre) <= ''%HASTA%''\r\nORDER BY ges_locales.IdLocal ASC,FechaCierre DESC', 'admin', 0, 'Finanzas', 0);
;;;;;;

INSERT INTO `ges_listados` VALUES ('', 'ARQUEO CAJA GENERAL', 'SELECT ges_locales.NombreComercial as Local, DATE_FORMAT(FechaCierre,''%d/%m/%Y %H:%i'') AS ''Fecha Cierre'', Simbolo as Moneda, ROUND(ImporteApertura,2) as ''Importe Apertura'', ROUND(ImporteIngresos,2) as ''Importe Ingreso'', ROUND(ImporteCompras,2) as ''Importe Compras'', ROUND(ImporteGastos,2) as ''Importe Gastos'', ROUND(ImporteAportaciones,2) as ''Importe Aportacion'', ROUND(ImporteSustracciones,2) as ''Importe Sustraccion'', ROUND(ImporteTeoricoCierre,2) as ''Importe Teorico Cierre'', ROUND(ImporteCierre,2) as ''Importe Cierre'',  ROUND(ImporteDescuadre,2) as ''Importe Descuadre'', ges_usuarios.Identificacion as Usuario   \r\nFROM ges_arqueo_cajagral  \r\nINNER JOIN ges_locales ON ges_arqueo_cajagral.IdLocal = ges_locales.IdLocal \r\nINNER JOIN ges_moneda ON ges_arqueo_cajagral.IdMoneda = ges_moneda.IdMoneda \r\nINNER JOIN ges_usuarios ON ges_arqueo_cajagral.IdUsuario = ges_usuarios.IdUsuario\r\nWHERE ges_arqueo_cajagral.Eliminado = 0  \r\nAND ges_arqueo_cajagral.IdLocal like ''%IDTIENDA%'' \r\nAND DATE(FechaCierre) >= ''%DESDE%'' \r\nAND DATE(FechaCierre) <= ''%HASTA%''\r\nORDER BY ges_locales.IdLocal ASC,FechaCierre DESC', 'admin', 0, 'Finanzas', 0);
;;;;;;

INSERT INTO `ges_listados` VALUES ('', 'MOVIMIENTOS DE CAJA GENERAL', 'SELECT ges_locales.NombreComercial as Local,DATE_FORMAT(ges_arqueo_cajagral.FechaApertura,''%d/%m/%y'') as ''Arqueo Apertura'', DATE_FORMAT(ges_arqueo_cajagral.FechaCierre,''%d/%m/%y'') as ''Arqueo Cierre'',ges_usuarios.Identificacion AS Usuario, IF(IdPartidaCaja = 0,''Ventas'',(SELECT PartidaCaja FROM ges_partidascaja WHERE ges_partidascaja.IdPartidaCaja = ges_librodiario_cajagral.IdPartidaCaja)) AS ''Partida'', DATE_FORMAT(FechaInsercion,''%d/%m/%Y %H:%s'') as ''Fecha Operación'', ges_librodiario_cajagral.TipoOperacion AS Operación, IF(IdPagoProvDoc = 0,''EFECTIVO'',(SELECT ges_modalidadespago.ModalidadPago FROM ges_modalidadespago INNER JOIN ges_pagosprovdoc ON ges_modalidadespago.IdModalidadPago = ges_pagosprovdoc.IdModalidadPago WHERE ges_pagosprovdoc.IdPagoProvDoc = ges_librodiario_cajagral.IdPagoProvDoc)) as ''Modalidad Pago'', Concepto, Simbolo as Moneda, ROUND(Importe,2) as Importe  \r\nFROM ges_librodiario_cajagral \r\nINNER JOIN ges_usuarios ON ges_librodiario_cajagral.IdUsuario = ges_usuarios.IdUsuario \r\nINNER JOIN ges_moneda ON ges_librodiario_cajagral.IdMoneda = ges_moneda.IdMoneda\r\nINNER JOIN ges_locales ON ges_librodiario_cajagral.IdLocal = ges_locales.IdLocal \r\nINNER JOIN ges_arqueo_cajagral ON ges_librodiario_cajagral.IdArqueoCajaGral = ges_arqueo_cajagral.IdArqueoCajaGral\r\nWHERE ges_librodiario_cajagral.Eliminado = 0 \r\nAND DATE(FechaInsercion) >= ''%DESDE%'' \r\nAND DATE(FechaInsercion) <= ''%HASTA%''\r\nAND ges_librodiario_cajagral.IdLocal like ''%IDTIENDA%'' \r\nAND ges_librodiario_cajagral.Importe > 0 \r\nAND ges_librodiario_cajagral.TipoOperacion like ''%TIPOOPCJAGRAL%''\r\nAND ges_librodiario_cajagral.IdMoneda like ''%IDMONEDA%''\r\nORDER BY ges_arqueo_cajagral.FechaApertura ASC,ges_librodiario_cajagral.TipoOperacion ASC, Partida ASC', 'admin', 0, 'Finanzas', 0);
;;;;;;

INSERT INTO `ges_listados` VALUES ('', 'CONSOLIDADO DE PARTIDAS CAJA TPV', 'SELECT PartidaCaja as ''Partida'', ROUND(SUM(Importe),2) AS ''Importe %SML%''\r\nFROM ges_dinero_movimientos\r\nINNER JOIN ges_partidascaja ON ges_dinero_movimientos.IdPartidaCaja = ges_partidascaja.IdPartidaCaja\r\nWHERE ges_dinero_movimientos.Eliminado = 0 \r\nAND DATE(ges_dinero_movimientos.FechaPago) >= ''%DESDE%'' \r\nAND DATE(ges_dinero_movimientos.FechaPago) <= ''%HASTA%''\r\nAND ges_dinero_movimientos.IdLocal like ''%IDTIENDA%'' \r\nAND ges_dinero_movimientos.IdPartidaCaja <> 0\r\nGROUP BY ges_dinero_movimientos.IdPartidaCaja\r\nORDER BY Partida ASC', 'admin', 0, 'Finanzas', 0);
;;;;;;

INSERT INTO `ges_listados` VALUES ('', 'MOVIMIENTOS DE PARTIDAS CAJA TPV', 'SELECT ges_usuarios.Identificacion as Usuario,DATE_FORMAT(FechaPago,''%d/%m/%Y %H:%s'') as ''Fecha Operación'',ges_dinero_movimientos.TipoOperacion as Operación, PartidaCaja as ''Partida Caja'',Concepto, ROUND(ges_dinero_movimientos.Importe,2) as ''Importe %SML%''\r\nFROM ges_dinero_movimientos\r\nINNER JOIN ges_partidascaja ON ges_dinero_movimientos.IdPartidaCaja = ges_partidascaja.IdPartidaCaja\r\nINNER JOIN ges_usuarios ON ges_dinero_movimientos.IdUsuario = ges_usuarios.IdUsuario\r\nWHERE ges_dinero_movimientos.Eliminado = 0\r\nAND ges_dinero_movimientos.IdLocal like ''%IDTIENDA%''\r\nAND DATE(FechaPago) >= ''%DESDE%'' \r\nAND DATE(FechaPago) <= ''%HASTA%''\r\nAND ges_partidascaja.TipoCaja <> ''CG''\r\nORDER BY ges_dinero_movimientos.TipoOperacion ASC, PartidaCaja ASC, FechaPago ASC', 'admin', 0, 'Finanzas', 0);
;;;;;;

INSERT INTO `ges_listados` VALUES ('', 'LOTE PRODUCCION - VENTA', 'SELECT ges_locales.NombreComercial as Local,ges_comprobantestipo.TipoComprobante as Comprobante, CONCAT(ges_comprobantestipo.Serie,'' - '',ges_comprobantesnum.NumeroComprobante) as ''Serie-Nro'', DATE_FORMAT(ges_comprobantesnum.Fecha,''%d/%m/%Y %H:%i'') as ''Fecha Emisión'',ges_clientes.NombreLegal  as Clientes\r\n,ges_productos.CodigoBarras AS CB,ges_productos.Referencia AS CR, CONCAT(ges_productos_idioma.Descripcion,'' '', Marca,'' '', ges_modelos.Color,'' '', ges_detalles.Talla,'' '', ges_laboratorios.NombreLegal) As Producto, ges_pedidosdet.Lote \r\nFROM ges_pedidosdet \r\nINNER JOIN ges_pedidos ON ges_pedidosdet.IdPedido = ges_pedidos.IdPedido \r\nINNER JOIN ges_locales ON ges_pedidos.IdLocal = ges_locales.Idlocal \r\nINNER JOIN ges_productos ON ges_pedidosdet.IdProducto = ges_productos.IdProducto \r\nINNER JOIN ges_productos_idioma ON ges_productos.IdProdBase = ges_productos_idioma.IdProdBase \r\nINNER JOIN ges_marcas ON ges_productos.IdMarca = ges_marcas.IdMarca \r\nINNER JOIN ges_modelos ON ges_productos.IdColor = ges_modelos.IdColor \r\nINNER JOIN ges_detalles ON ges_productos.IdTalla = ges_detalles.IdTalla \r\nINNER JOIN ges_laboratorios ON ges_productos.IdLabHab = ges_laboratorios.IdLaboratorio \r\nINNER JOIN ges_comprobantesdet ON ges_pedidosdet.IdPedidodet = ges_comprobantesdet.IdPedidoDet\r\nINNER JOIN ges_comprobantes ON ges_comprobantesdet.IdComprobante = ges_comprobantes.IdComprobante\r\nINNER JOIN ges_clientes ON ges_comprobantes.IdCliente = ges_clientes.IdCliente\r\nINNER JOIN ges_comprobantesnum ON ges_comprobantes.IdComprobante = ges_comprobantesnum.IdComprobante\r\nINNER JOIN ges_comprobantestipo ON ges_comprobantesnum.IdTipoComprobante = ges_comprobantestipo.IdTipoComprobante\r\nWHERE ges_pedidosdet.Eliminado = 0 \r\nAND ges_productos.Lote = 1\r\nAND ges_pedidosdet.Lote like ''%%LOTE%%''', 'admin', 0, 'Busquedas', 0);
;;;;;;

INSERT INTO `ges_listados` VALUES ('', 'PRODUCTOS CON MAYOR MOVIMIENTO', 'SELECT ges_locales.NombreComercial as Local, ges_comprobantesdet.CodigoBarras as ''Código Barras'', ges_comprobantesdet.Referencia, CONCAT(ges_productos_idioma.Descripcion,'' '',Marca,'' '',Color,'' '',Talla,'' '',ges_laboratorios.NombreComercial) As Producto, SUM(ges_comprobantesdet.Cantidad) AS Cantidad, ROUND(AVG(ges_comprobantesdet.Precio),2) As ''Precio Promedio''\r\nFROM ges_comprobantes \r\nINNER JOIN ges_comprobantesdet ON ges_comprobantes.IdComprobante = ges_comprobantesdet.IdComprobante \r\nINNER JOIN ges_productos ON ges_comprobantesdet.IdProducto = ges_productos.IdProducto \r\nINNER JOIN ges_productos_idioma ON ges_productos.IdProdBase = ges_productos_idioma.IdProdBase \r\nINNER JOIN ges_familias ON ges_productos.IdFamilia = ges_familias.IdFamilia\r\nINNER JOIN ges_marcas ON ges_marcas.IdMarca = ges_productos.IdMarca \r\nINNER JOIN ges_laboratorios ON ges_laboratorios.IdLaboratorio = ges_productos.IdLabHab \r\nINNER JOIN ges_comprobantesnum ON ges_comprobantes.IdComprobante = ges_comprobantesnum.IdComprobante \r\nINNER JOIN ges_comprobantestipo ON ges_comprobantesnum.IdTipoComprobante = ges_comprobantestipo.IdTipoComprobante \r\nINNER JOIN ges_locales ON ges_comprobantes.IdLocal = ges_locales.IdLocal\r\nAND DATE(ges_comprobantes.FechaComprobante) >= ''%DESDE%'' \r\nAND DATE(ges_comprobantes.FechaComprobante) <= ''%HASTA%'' \r\nAND ges_comprobantes.IdLocal like ''%IDTIENDA%'' \r\nAND ges_productos.IdFamilia like ''%IDFAMILIA%''\r\nAND ges_productos.IdMarca like ''%IDMARCA%''\r\nAND ges_comprobantestipo.TipoComprobante IN (''Factura'',''Boleta'',''Ticket'',''Albaran'') \r\nAND ges_comprobantesnum.Status <> ''Anulado'' \r\nAND ges_comprobantes.Eliminado = 0 \r\nGROUP BY ges_productos.IdProducto,ges_locales.Idlocal \r\nORDER BY ges_locales.IdLocal,Cantidad DESC, Producto ASC \r\n', 'admin', 0, 'Ventas', 0);
;;;;;;

INSERT INTO `ges_listados` VALUES ('', 'PRODUCTOS CON MAYOR UTILIDAD', 'SELECT ges_locales.NombreComercial as Local, ges_comprobantesdet.CodigoBarras as ''Código Barras'', ges_comprobantesdet.Referencia, CONCAT(ges_productos_idioma.Descripcion,'' '',Marca,'' '',Color,'' '',Talla,'' '',ges_laboratorios.NombreComercial) As Producto, SUM(ges_comprobantesdet.Cantidad) AS Cantidad, ROUND(AVG(ges_comprobantesdet.CostoUnitario),2) as Costo, ROUND(AVG(ges_comprobantesdet.Precio),2) As ''Precio Promedio'', ges_comprobantesdet.Impuesto as ''IGV (%)'', ROUND((SUM(ges_comprobantesdet.Cantidad)*(AVG(ges_comprobantesdet.Precio)*100/(100+ges_comprobantesdet.Impuesto) - AVG(ges_comprobantesdet.CostoUnitario))),2) as Utilidad \r\nFROM ges_comprobantes \r\nINNER JOIN ges_comprobantesdet ON ges_comprobantes.IdComprobante = ges_comprobantesdet.IdComprobante \r\nINNER JOIN ges_productos ON ges_comprobantesdet.IdProducto = ges_productos.IdProducto \r\nINNER JOIN ges_productos_idioma ON ges_productos.IdProdBase = ges_productos_idioma.IdProdBase \r\nINNER JOIN ges_familias ON ges_productos.IdFamilia = ges_familias.IdFamilia\r\nINNER JOIN ges_marcas ON ges_marcas.IdMarca = ges_productos.IdMarca \r\nINNER JOIN ges_laboratorios ON ges_laboratorios.IdLaboratorio = ges_productos.IdLabHab \r\nINNER JOIN ges_comprobantesnum ON ges_comprobantes.IdComprobante = ges_comprobantesnum.IdComprobante \r\nINNER JOIN ges_comprobantestipo ON ges_comprobantesnum.IdTipoComprobante = ges_comprobantestipo.IdTipoComprobante \r\nINNER JOIN ges_locales ON ges_comprobantes.IdLocal = ges_locales.IdLocal\r\nAND DATE(ges_comprobantes.FechaComprobante) >= ''%DESDE%'' \r\nAND DATE(ges_comprobantes.FechaComprobante) <= ''%HASTA%'' \r\nAND ges_comprobantes.IdLocal like ''%IDTIENDA%'' \r\nAND ges_productos.IdFamilia like ''%IDFAMILIA%''\r\nAND ges_productos.IdMarca like ''%IDMARCA%''\r\nAND ges_comprobantestipo.TipoComprobante IN (''Factura'',''Boleta'',''Ticket'',''Albaran'') \r\nAND ges_comprobantesnum.Status <> ''Anulado'' \r\nAND ges_comprobantes.Eliminado = 0 \r\nGROUP BY ges_productos.IdProducto,ges_locales.Idlocal \r\nORDER BY ges_locales.IdLocal,Utilidad DESC', 'admin', 0, 'Ventas', 0);
;;;;;;

INSERT INTO `ges_listados` VALUES ('', 'POR PRODUCTO', 'SELECT ges_locales.NombreComercial as Local, DATE_FORMAT(ges_comprobantesnum.Fecha,''%d/%m/%y %H:%i'') as ''Fecha Operación'', ges_comprobantesdet.CodigoBarras as ''Código Barras'', CONCAT(ges_productos_idioma.Descripcion,'' '',Marca,'' '',Color,'' '',Talla,'' '',ges_laboratorios.NombreComercial) As Producto, ges_comprobantestipo.TipoComprobante as Comprobante,CONCAT(ges_comprobantes.SerieComprobante,''-'',ges_comprobantes.NComprobante) as Código, CONCAT(ges_comprobantestipo.Serie,'' - '',ges_comprobantesnum.NumeroComprobante) as ''Nro. Comprobante'', ges_comprobantesdet.Cantidad, ROUND(ges_comprobantesdet.Precio,2) as Precio, ROUND(ges_comprobantesdet.Importe,2) as Importe\r\nFROM ges_comprobantes \r\nINNER JOIN ges_comprobantesdet ON ges_comprobantes.IdComprobante = ges_comprobantesdet.IdComprobante \r\nINNER JOIN ges_productos ON ges_comprobantesdet.IdProducto = ges_productos.IdProducto \r\nINNER JOIN ges_productos_idioma ON ges_productos.IdProdBase = ges_productos_idioma.IdProdBase \r\nINNER JOIN ges_familias ON ges_productos.IdFamilia = ges_familias.IdFamilia\r\nINNER JOIN ges_marcas ON ges_marcas.IdMarca = ges_productos.IdMarca \r\nINNER JOIN ges_laboratorios ON ges_laboratorios.IdLaboratorio = ges_productos.IdLabHab \r\nINNER JOIN ges_comprobantesnum ON ges_comprobantes.IdComprobante = ges_comprobantesnum.IdComprobante \r\nINNER JOIN ges_comprobantestipo ON ges_comprobantesnum.IdTipoComprobante = ges_comprobantestipo.IdTipoComprobante \r\nINNER JOIN ges_locales ON ges_comprobantes.IdLocal = ges_locales.IdLocal\r\nAND DATE(ges_comprobantes.FechaComprobante) >= ''%DESDE%'' \r\nAND DATE(ges_comprobantes.FechaComprobante) <= ''%HASTA%'' \r\nAND ges_comprobantes.IdLocal like ''%IDTIENDA%'' \r\nAND ges_comprobantesdet.CodigoBarras like ''%%CODIGOBARRAS%%''\r\nAND ges_comprobantestipo.TipoComprobante IN (''Factura'',''Boleta'',''Ticket'',''Albaran'') \r\nAND ges_comprobantesnum.Status <> ''Anulado''\r\nAND ges_comprobantestipo.TipoComprobante like ''%TIPOCOMPROBANTE%''\r\n''%TIPOVENTATPV%'' \r\n''%VENTAESTADO%'' \r\nAND ges_comprobantes.Eliminado = 0 \r\nORDER BY ges_locales.IdLocal,ges_comprobantes.IdComprobante, Producto ASC\r\n', 'admin', 0, 'Ventas', 0);
;;;;;;

INSERT INTO `ges_listados` VALUES ('', 'POR CLIENTES', 'SELECT ges_locales.NombreComercial as Local, DATE_FORMAT(ges_comprobantesnum.Fecha,''%d/%m/%y %H:%i'') as ''Fecha Operación'',ges_clientes.TipoCliente AS ''Tipo Cliente'', IF(ges_clientes.TipoCliente = ''Empresa'',ges_clientes.NombreLegal,ges_clientes.NombreComercial) as Cliente, ges_clientes.NumeroFiscal as ''DNI/RUC'', ges_comprobantestipo.TipoComprobante as Comprobante,CONCAT(ges_comprobantes.SerieComprobante,''-'',ges_comprobantes.NComprobante) as Código, CONCAT(ges_comprobantestipo.Serie,'' - '',ges_comprobantesnum.NumeroComprobante) as ''Serie-Nro'', ROUND(ges_comprobantes.TotalImporte,2) as ''Importe %SML%'', ROUND(ges_comprobantes.ImportePendiente,2) as ''Pendiente %SML%''\r\nFROM ges_comprobantes \r\nINNER JOIN ges_comprobantesnum ON ges_comprobantes.IdComprobante = ges_comprobantesnum.IdComprobante \r\nINNER JOIN ges_comprobantestipo ON ges_comprobantesnum.IdTipoComprobante = ges_comprobantestipo.IdTipoComprobante \r\nINNER JOIN ges_locales ON ges_comprobantes.IdLocal = ges_locales.IdLocal\r\nINNER JOIN ges_clientes ON ges_comprobantes.IdCliente = ges_clientes.IdCliente\r\nAND DATE(ges_comprobantes.FechaComprobante) >= ''%DESDE%'' \r\nAND DATE(ges_comprobantes.FechaComprobante) <= ''%HASTA%'' \r\nAND ges_comprobantes.IdLocal like ''%IDTIENDA%'' \r\nAND ges_clientes.NumeroFiscal like ''%DNICLIENTE%''\r\nAND ges_clientes.NombreComercial like ''%%CLIENTE%%''\r\nAND ges_clientes.TipoCliente like ''%TIPOCLIENTE%''\r\nAND ges_comprobantestipo.TipoComprobante IN (''Factura'',''Boleta'',''Ticket'',''Albaran'') \r\nAND ges_comprobantesnum.Status <> ''Anulado'' \r\nAND ges_comprobantes.Eliminado = 0 \r\nAND ges_clientes.TipoCliente <> ''Interno''\r\nORDER BY ges_locales.IdLocal,''Importe %SML%'' DESC\r\n', 'admin', 0, 'Ventas', 0);
;;;;;;

INSERT INTO `ges_listados` VALUES ('', 'CLIENTES', 'SELECT IF(ges_clientes.IdLocal = 0,''GENERAL'',(SELECT ges_locales.NombreComercial FROM ges_locales WHERE ges_locales.IdLocal = ges_clientes.IdLocal)) as Local, TipoCliente as ''Tipo Cliente'', IF(TipoCliente IN (''Empresa'',''Gobierno''),ges_clientes.NombreLegal,ges_clientes.NombreComercial) as Cliente, DATE_FORMAT(ges_clientes.FechaRegistro,''%d/%m/%Y'') as ''Fecha Registro'', ges_clientes.NumeroFiscal as ''DNI/RUC'', ges_clientes.Direccion as Dirección, ges_clientes.Telefono1 as ''Teléfono'', ges_clientes.Email, ROUND(ges_clientes.Descuento,2) as ''Descuento'', ROUND(Bono,2) as ''Bono''\r\nFROM ges_clientes\r\nWHERE ges_clientes.Eliminado = 0\r\nAND ges_clientes.IdCliente > 0\r\nAND TipoCliente <>''Interno''\r\nAND ges_clientes.IdLocal like ''%IDTIENDA%''\r\nORDER BY ges_clientes.FechaRegistro DESC, Cliente ASC', 'admin', 0, 'Listas', 0);
;;;;;;

INSERT INTO `ges_listados` VALUES ('', 'CON REGISTRO SANITARIO', 'SELECT ges_locales.NombreLegal AS Local, ges_productos.CodigoBarras as ''Código Barras'', CONCAT(ges_productos_idioma.Descripcion,'' '', Marca,'' '', ges_modelos.Color,'' '', ges_detalles.Talla,'' '', ges_laboratorios.NombreComercial) As Producto, RefProvHab AS ''Registro Sanitario'', Unidades, ROUND(PrecioVenta,2) AS ''Precio %SML%''\r\nFROM ges_almacenes\r\nINNER JOIN ges_locales ON ges_almacenes.IdLocal = ges_locales.IdLocal \r\nINNER JOIN ges_productos ON ges_almacenes.IdProducto = ges_productos.IdProducto \r\nINNER JOIN ges_productos_idioma ON ges_productos.IdProdBase = ges_productos_idioma.IdProdBase \r\nINNER JOIN ges_marcas ON ges_productos.IdMarca = ges_marcas.IdMarca \r\nINNER JOIN ges_modelos ON ges_productos.IdColor = ges_modelos.IdColor \r\nINNER JOIN ges_detalles ON ges_productos.IdTalla = ges_detalles.IdTalla \r\nINNER JOIN ges_laboratorios ON ges_productos.IdLabHab = ges_laboratorios.IdLaboratorio\r\nWHERE ges_almacenes.Unidades > 0\r\nAND ges_productos.RefProvHab <>''''\r\nAND ges_almacenes.IdLocal like ''%IDTIENDA%''', 'admin', 0, 'Productos', 0);
;;;;;;

INSERT INTO `ges_listados` VALUES ('', 'CON CONDICION DE VENTA', 'SELECT ges_locales.NombreComercial as Local, ges_productos.CodigoBarras as ''Código Barras'', ges_productos.Referencia, CONCAT(ges_productos_idioma.Descripcion,'' '',Marca,'' '',Color,'' '',Talla,'' '',ges_laboratorios.NombreComercial) As Producto, Unidades as Cantidad, ROUND(PrecioVenta,2) as Precio, IF(CondicionVenta = ''0'',''Sin Receta'',(IF(CondicionVenta = ''CRM'',''Con Receta'',''Con Receta Retenida''))) as ''Condición Venta''\r\nFROM ges_productos \r\nINNER JOIN ges_productos_idioma ON ges_productos.IdProdBase = ges_productos_idioma.IdProdBase \r\nINNER JOIN ges_familias ON ges_productos.IdFamilia = ges_familias.IdFamilia\r\nINNER JOIN ges_marcas ON ges_marcas.IdMarca = ges_productos.IdMarca \r\nINNER JOIN ges_laboratorios ON ges_laboratorios.IdLaboratorio = ges_productos.IdLabHab \r\nINNER JOIN ges_almacenes ON ges_productos.IdProducto = ges_almacenes.IdProducto\r\nINNER JOIN ges_locales ON ges_almacenes.IdLocal = ges_locales.IdLocal\r\nINNER JOIN ges_modelos ON ges_productos.IdColor = ges_modelos.IdColor\r\nINNER JOIN ges_detalles ON ges_productos.IdTalla = ges_detalles.IdTalla\r\nAND ges_locales.IdLocal like ''%IDTIENDA%'' \r\nAND ges_productos.IdFamilia like ''%IDFAMILIA%''\r\nAND ges_productos.IdMarca like ''%IDMARCA%''\r\nAND ges_productos.CondicionVenta like ''%CONDICIONVENTA%''\r\nAND ges_productos.Eliminado = 0 \r\nORDER BY ges_locales.Idlocal,CondicionVenta ASC \r\n', 'admin', 0, 'Productos', 0);
;;;;;;

INSERT INTO `ges_listados` VALUES ('', 'INCIDENCIAS', 'SELECT ges_locales.NombreComercial as Local, ges_clientes.NombreComercial as Cliente, ges_ordenservicio.Codigo as Código, ges_ordenservicio.Estado, ges_ordenservicio.Prioridad,ges_ordenservicio.Facturacion as Facturación, ges_ordenservicio.Impuesto, ges_ordenservicio.Importe, ges_usuarios.Identificacion as ''Resp. Ingreso'', IF(ges_ordenservicio.IdUsuarioEntrega = 0,'' '',(SELECT Identificacion FROM ges_usuarios WHERE ges_usuarios.IdUsuario = ges_ordenservicio.IdUsuarioEntrega)) as ''Resp. Salida'' \r\nFROM ges_ordenservicio\r\nINNER JOIN ges_locales ON ges_ordenservicio.IdLocal = ges_locales.IdLocal\r\nINNER JOIN ges_clientes ON ges_ordenservicio.IdCliente = ges_clientes.IdCliente\r\nINNER JOIN ges_usuarios ON ges_ordenservicio.IdUsuario = ges_usuarios.IdUsuario\r\nWHERE ges_ordenservicio.Estado like ''%ESTADOOS%''\r\nAND ges_ordenservicio.IdLocal like ''%IDTIENDA%''\r\nAND ges_ordenservicio.Prioridad like ''%PRIORIDAD%''\r\nAND ges_ordenservicio.IdUsuario like ''%IDUSUARIO%''\r\nAND ges_ordenservicio.Facturacion like ''%FACTURACION%''\r\nAND ges_ordenservicio.Codigo like ''%CODIGO%''\r\nAND date(ges_ordenservicio.FechaIngreso) >= ''%DESDE%''\r\nAND date(ges_ordenservicio.FechaIngreso) <= ''%HASTA%''\r\nORDER BY ges_ordenservicio.Prioridad DESC', 'admin', 0, 'SAT', 0);
;;;;;;

INSERT INTO `ges_listados` VALUES ('', 'INCIDENCIAS', 'SELECT ges_clientes.NombreComercial as Cliente, ges_ordenservicio.Codigo as Código, ges_ordenservicio.Estado, ges_ordenservicio.Prioridad,ges_ordenservicio.Facturacion as Facturación, ges_ordenservicio.Impuesto, ges_ordenservicio.Importe, ges_usuarios.Identificacion as ''Resp. Ingreso'', IF(ges_ordenservicio.IdUsuarioEntrega = 0,'' '',(SELECT Identificacion FROM ges_usuarios WHERE ges_usuarios.IdUsuario = ges_ordenservicio.IdUsuarioEntrega)) as ''Resp. Salida'' \r\nFROM ges_ordenservicio\r\nINNER JOIN ges_locales ON ges_ordenservicio.IdLocal = ges_locales.IdLocal\r\nINNER JOIN ges_clientes ON ges_ordenservicio.IdCliente = ges_clientes.IdCliente\r\nINNER JOIN ges_usuarios ON ges_ordenservicio.IdUsuario = ges_usuarios.IdUsuario\r\nWHERE ges_ordenservicio.Estado like ''%ESTADOOS%''\r\nAND ges_ordenservicio.IdLocal like ''%IDTIENDA%''\r\nAND ges_ordenservicio.Prioridad like ''%PRIORIDAD%''\r\nAND ges_ordenservicio.IdUsuario like ''%IDUSUARIO%''\r\nAND ges_ordenservicio.Facturacion like ''%FACTURACION%''\r\nAND ges_ordenservicio.Codigo like ''%CODIGO%''\r\nAND date(ges_ordenservicio.FechaIngreso) >= ''%DESDE%''\r\nAND date(ges_ordenservicio.FechaIngreso) <= ''%HASTA%''\r\nORDER BY ges_ordenservicio.Prioridad DESC', 'TPV', 0, 'SAT', 0);
;;;;;;

INSERT INTO `ges_listados` VALUES ('', 'SERVICIOS', 'SELECT ges_locales.NombreComercial as Local, ges_clientes.NombreComercial as Cliente, ges_ordenservicio.Codigo as Código, ges_productos_idioma.Descripcion as Servicio, ges_ordenserviciodet.Estado, ges_ordenserviciodet.Concepto, ges_ordenserviciodet.FechaInicio as ''Fecha Asignación'', ges_ordenserviciodet.EstadoSolucion as Solución, ges_ordenserviciodet.Importe, IF(ges_ordenserviciodet.IdUsuarioResponsable = 0,'' '',(SELECT Identificacion FROM ges_usuarios WHERE ges_usuarios.IdUsuario = ges_ordenserviciodet.IdUsuarioResponsable)) as Responsable \r\nFROM ges_ordenserviciodet\r\nINNER JOIN ges_ordenservicio ON ges_ordenserviciodet.IdOrdenServicio = ges_ordenservicio.IdOrdenServicio\r\nINNER JOIN ges_locales ON ges_ordenservicio.IdLocal = ges_locales.IdLocal\r\nINNER JOIN ges_clientes ON ges_ordenservicio.IdCliente = ges_clientes.IdCliente\r\nINNER JOIN ges_productos ON ges_ordenserviciodet.IdProducto = ges_productos.IdProducto\r\nINNER JOIN ges_productos_idioma ON ges_productos.IdProdBase = ges_productos_idioma.IdProdBase\r\nWHERE ges_ordenserviciodet.Estado like ''%ESTADOOS%''\r\nAND ges_ordenservicio.IdLocal like ''%IDTIENDA%''\r\nAND ges_ordenserviciodet.IdUsuarioResponsable like ''%IDUSUARIO%''\r\nAND ges_ordenservicio.Codigo like ''%CODIGO%''\r\nAND date(ges_ordenservicio.FechaIngreso) >= ''%DESDE%''\r\nAND date(ges_ordenservicio.FechaIngreso) <= ''%HASTA%''\r\nAND ges_productos.Servicio <> 0', 'admin', 0, 'SAT', 0);
;;;;;;

INSERT INTO `ges_listados` VALUES ('', 'SERVICIOS', 'SELECT ges_clientes.NombreComercial as Cliente, ges_ordenservicio.Codigo as Código, ges_productos_idioma.Descripcion as Servicio, ges_ordenserviciodet.Estado, ges_ordenserviciodet.Concepto, ges_ordenserviciodet.FechaInicio as ''Fecha Asignación'', ges_ordenserviciodet.EstadoSolucion as Solución, ges_ordenserviciodet.Importe, IF(ges_ordenserviciodet.IdUsuarioResponsable = 0,'' '',(SELECT Identificacion FROM ges_usuarios WHERE ges_usuarios.IdUsuario = ges_ordenserviciodet.IdUsuarioResponsable)) as Responsable \r\nFROM ges_ordenserviciodet\r\nINNER JOIN ges_ordenservicio ON ges_ordenserviciodet.IdOrdenServicio = ges_ordenservicio.IdOrdenServicio\r\nINNER JOIN ges_locales ON ges_ordenservicio.IdLocal = ges_locales.IdLocal\r\nINNER JOIN ges_clientes ON ges_ordenservicio.IdCliente = ges_clientes.IdCliente\r\nINNER JOIN ges_productos ON ges_ordenserviciodet.IdProducto = ges_productos.IdProducto\r\nINNER JOIN ges_productos_idioma ON ges_productos.IdProdBase = ges_productos_idioma.IdProdBase\r\nWHERE ges_ordenserviciodet.Estado like ''%ESTADOOS%''\r\nAND ges_ordenservicio.IdLocal like ''%IDTIENDA%''\r\nAND ges_ordenserviciodet.IdUsuarioResponsable like ''%IDUSUARIO%''\r\nAND ges_ordenservicio.Codigo like ''%CODIGO%''\r\nAND date(ges_ordenservicio.FechaIngreso) >= ''%DESDE%''\r\nAND date(ges_ordenservicio.FechaIngreso) <= ''%HASTA%''\r\nAND ges_productos.Servicio <> 0', 'TPV', 0, 'SAT', 0);
;;;;;;

INSERT INTO `ges_listados` VALUES ('', 'SUSCRIPCIONES', 'SELECT ges_locales.NombreComercial as Local, ges_clientes.NombreComercial as Cliente, ges_suscripciontipo.TipoSuscripcion as Suscripción, ges_suscripciones.Estado, DATE_FORMAT(ges_suscripciones.FechaInicio,''%d/%m/%Y'') as Inicia, IF(ges_suscripciones.FechaFin like ''0000-00-00'','' '',(DATE_FORMAT(ges_suscripciones.FechaInicio,''%d/%m/%Y''))) as Finaliza, ges_suscripciones.TipoPago as ''Tipo Pago'', ges_suscripciones.Prolongacion as Prolongación , ges_suscripciones.Comprobante, ges_suscripciones.SerieComprobante as Serie, ges_suscripciones.Observaciones, ges_usuarios.Identificacion as Usuario\r\nFROM ges_suscripciones\r\nINNER JOIN ges_locales ON ges_suscripciones.IdLocal = ges_locales.IdLocal\r\nINNER JOIN ges_clientes ON ges_suscripciones.IdCliente = ges_clientes.IdCliente\r\nINNER JOIN ges_usuarios ON ges_suscripciones.IdUsuario = ges_usuarios.IdUsuario\r\nINNER JOIN ges_suscripciontipo ON ges_suscripciones.IdTipoSuscripcion = ges_suscripciontipo.IdTipoSuscripcion\r\nWHERE ges_suscripciones.Eliminado = 0\r\nAND ges_suscripciones.Estado like ''%ESTADOSUSCRIPCION%''\r\nAND ges_suscripciontipo.TipoSuscripcion like ''%TIPOSUSCRIPCION%''\r\nAND ges_suscripciones.TipoPago like ''%TIPOPAGOSUSCRIPCION%''\r\nAND ges_suscripciones.Prolongacion like ''%PROLONGACION%''\r\nAND ges_suscripciones.Comprobante like ''%TIPOCOMPROBANTE%''\r\nAND ges_clientes.NumeroFiscal like ''%DNICLIENTE%''\r\nAND ges_suscripciones.IdLocal like ''%IDTIENDA%''\r\nAND DATE(ges_suscripciones.FechaRegistro) >= ''%DESDE%''\r\nAND DATE(ges_suscripciones.FechaRegistro) <= ''%HASTA%''', 'admin', 0, 'Suscripciones', 0);
;;;;;;

INSERT INTO `ges_listados` VALUES ('', 'SUSCRIPCIONES', 'SELECT ges_clientes.NombreComercial as Cliente, ges_suscripciontipo.TipoSuscripcion as Suscripción, ges_suscripciones.Estado, DATE_FORMAT(ges_suscripciones.FechaInicio,''%d/%m/%Y'') as Inicia, IF(ges_suscripciones.FechaFin like ''0000-00-00'','' '',(DATE_FORMAT(ges_suscripciones.FechaInicio,''%d/%m/%Y''))) as Finaliza, ges_suscripciones.TipoPago as ''Tipo Pago'', ges_suscripciones.Prolongacion as Prolongación, ges_suscripciones.Comprobante, ges_suscripciones.SerieComprobante as Serie, ges_suscripciones.Observaciones, ges_usuarios.Identificacion as Usuario\r\nFROM ges_suscripciones\r\nINNER JOIN ges_locales ON ges_suscripciones.IdLocal = ges_locales.IdLocal\r\nINNER JOIN ges_clientes ON ges_suscripciones.IdCliente = ges_clientes.IdCliente\r\nINNER JOIN ges_usuarios ON ges_suscripciones.IdUsuario = ges_usuarios.IdUsuario\r\nINNER JOIN ges_suscripciontipo ON ges_suscripciones.IdTipoSuscripcion = ges_suscripciontipo.IdTipoSuscripcion\r\nWHERE ges_suscripciones.Eliminado = 0\r\nAND ges_suscripciones.Estado like ''%ESTADOSUSCRIPCION%''\r\nAND ges_suscripciontipo.TipoSuscripcion like ''%TIPOSUSCRIPCION%''\r\nAND ges_suscripciones.TipoPago like ''%TIPOPAGOSUSCRIPCION%''\r\nAND ges_suscripciones.Prolongacion like ''%PROLONGACION%''\r\nAND ges_suscripciones.Comprobante like ''%TIPOCOMPROBANTE%''\r\nAND ges_clientes.NumeroFiscal like ''%DNICLIENTE%''\r\nAND ges_suscripciones.IdLocal like ''%IDTIENDA%''\r\nAND DATE(ges_suscripciones.FechaRegistro) >= ''%DESDE%''\r\nAND DATE(ges_suscripciones.FechaRegistro) <= ''%HASTA%''', 'TPV', 0, 'Suscripciones', 0)
;;;;;;

INSERT INTO `ges_listados` VALUES ('', 'INCIDENCIAS', 'SELECT ges_locales.NombreComercial as Local, ges_clientes.NombreComercial as Cliente, ges_suscripciontipo.TipoSuscripcion as Suscripción, ges_suscripcionincidentes.Estado, DATE_FORMAT(ges_suscripcionincidentes.FechaRegistro,''%d/%m/%Y %H:%i'') as Fecha, ges_suscripcionincidentes.TipoPago as ''Tipo Pago'', ges_suscripcionincidentes.Prolongacion as Prolongación, ges_suscripcionincidentes.Comprobante, ges_suscripcionincidentes.SerieComprobante as Serie, ges_suscripcionincidentes.Observaciones, ges_usuarios.Identificacion as Usuario\r\nFROM ges_suscripcionincidentes\r\nINNER JOIN ges_suscripciones ON ges_suscripcionincidentes.IdSuscripcion = ges_suscripciones.IdSuscripcion\r\nINNER JOIN ges_locales ON ges_suscripciones.IdLocal = ges_locales.IdLocal\r\nINNER JOIN ges_clientes ON ges_suscripciones.IdCliente = ges_clientes.IdCliente\r\nINNER JOIN ges_usuarios ON ges_suscripcionincidentes.IdUsuario = ges_usuarios.IdUsuario\r\nINNER JOIN ges_suscripciontipo ON ges_suscripcionincidentes.IdTipoSuscripcion = ges_suscripciontipo.IdTipoSuscripcion\r\nWHERE ges_suscripcionincidentes.Eliminado = 0\r\nAND ges_suscripcionincidentes.Estado like ''%ESTADOSUSCRIPCION%''\r\nAND ges_suscripciontipo.TipoSuscripcion like ''%TIPOSUSCRIPCION%''\r\nAND ges_clientes.NumeroFiscal like ''%DNICLIENTE%''\r\nAND ges_suscripciones.IdLocal like ''%IDTIENDA%''\r\nAND DATE(ges_suscripcionincidentes.FechaRegistro) >= ''%DESDE%''\r\nAND DATE(ges_suscripcionincidentes.FechaRegistro) <= ''%HASTA%''', 'admin', 0, 'Suscripciones', 0);
;;;;;;

INSERT INTO `ges_listados` VALUES ('', 'INCIDENCIAS', 'SELECT ges_clientes.NombreComercial as Cliente, ges_suscripciontipo.TipoSuscripcion as Suscripción, ges_suscripcionincidentes.Estado, DATE_FORMAT(ges_suscripcionincidentes.FechaRegistro,''%d/%m/%Y %H:%i'') as Fecha, ges_suscripcionincidentes.TipoPago as ''Tipo Pago'', ges_suscripcionincidentes.Prolongacion as Prolongación, ges_suscripcionincidentes.Comprobante, ges_suscripcionincidentes.SerieComprobante as Serie, ges_suscripcionincidentes.Observaciones, ges_usuarios.Identificacion as Usuario\r\nFROM ges_suscripcionincidentes\r\nINNER JOIN ges_suscripciones ON ges_suscripcionincidentes.IdSuscripcion = ges_suscripciones.IdSuscripcion\r\nINNER JOIN ges_locales ON ges_suscripciones.IdLocal = ges_locales.IdLocal\r\nINNER JOIN ges_clientes ON ges_suscripciones.IdCliente = ges_clientes.IdCliente\r\nINNER JOIN ges_usuarios ON ges_suscripcionincidentes.IdUsuario = ges_usuarios.IdUsuario\r\nINNER JOIN ges_suscripciontipo ON ges_suscripcionincidentes.IdTipoSuscripcion = ges_suscripciontipo.IdTipoSuscripcion\r\nWHERE ges_suscripcionincidentes.Eliminado = 0\r\nAND ges_suscripcionincidentes.Estado like ''%ESTADOSUSCRIPCION%''\r\nAND ges_suscripciontipo.TipoSuscripcion like ''%TIPOSUSCRIPCION%''\r\nAND ges_clientes.NumeroFiscal like ''%DNICLIENTE%''\r\nAND ges_suscripciones.IdLocal like ''%IDTIENDA%''\r\nAND DATE(ges_suscripcionincidentes.FechaRegistro) >= ''%DESDE%''\r\nAND DATE(ges_suscripcionincidentes.FechaRegistro) <= ''%HASTA%''', 'TPV', 0, 'Suscripciones', 0);
;;;;;;

INSERT INTO `ges_listados` VALUES ('', 'COMPROBANTES', 'SELECT ges_clientes.NombreComercial as Cliente, ges_suscripciontipo.TipoSuscripcion as Suscripción,DATE_FORMAT(ges_comprobantesnum.Fecha,''%d/%m/%Y %H:%i'') as ''Fecha Facturación'', ges_comprobantestipo.TipoComprobante as Comprobante, CONCAT(ges_comprobantestipo.Serie,''-'',ges_comprobantesnum.NumeroComprobante) as Código, IF(ges_comprobantes.ImportePendiente > 0, ''Pendiente'',''Pagado'') as ''Estado Pago'', ges_comprobantes.TotalImporte as Importe, ges_comprobantes.ImportePendiente as Pendiente, ges_usuarios.Identificacion as Usuario\r\nFROM ges_comprobantes\r\nINNER JOIN ges_clientes ON ges_comprobantes.IdCliente = ges_clientes.IdCliente\r\nINNER JOIN ges_usuarios ON ges_comprobantes.IdUsuario = ges_usuarios.IdUsuario\r\nINNER JOIN ges_comprobantesnum ON ges_comprobantes.IdComprobante = ges_comprobantesnum.IdComprobante\r\nINNER JOIN ges_comprobantestipo ON ges_comprobantesnum.IdTipoComprobante = ges_comprobantestipo.IdTipoComprobante\r\nINNER JOIN ges_suscripciones ON ges_comprobantes.IdSuscripcion = ges_suscripciones.IdSuscripcion\r\nINNER JOIN ges_suscripciontipo ON ges_suscripciones.IdTipoSuscripcion = ges_suscripciontipo.IdTipoSuscripcion\r\nWHERE ges_comprobantes.IdSuscripcion <> 0\r\nAND ges_comprobantes.IdLocal like ''%IDTIENDA%''\r\nAND DATE(ges_comprobantesnum.Fecha) >= ''%DESDE%''\r\nAND DATE(ges_comprobantesnum.Fecha) <= ''%HASTA%''\r\nAND ges_comprobantes.ImportePendiente ''%IMPORTE%''\r\nAND ges_clientes.NumeroFiscal like ''%DNICLIENTE%''', 'TPV', 0, 'Suscripciones', 0);
;;;;;;

INSERT INTO `ges_listados` VALUES ('', 'COMPROBANTES', 'SELECT ges_locales.NombreComercial as Local, ges_clientes.NombreComercial as Cliente, ges_suscripciontipo.TipoSuscripcion as Suscripción,DATE_FORMAT(ges_comprobantesnum.Fecha,''%d/%m/%Y %H:%i'') as ''Fecha Facturación'', ges_comprobantestipo.TipoComprobante as Comprobante, CONCAT(ges_comprobantestipo.Serie,''-'',ges_comprobantesnum.NumeroComprobante) as Código, IF(ges_comprobantes.ImportePendiente > 0, ''Pendiente'',''Pagado'') as ''Estado Pago'', ges_comprobantes.TotalImporte as Importe, ges_comprobantes.ImportePendiente as Pendiente, ges_usuarios.Identificacion as Usuario\r\nFROM ges_comprobantes\r\nINNER JOIN ges_clientes ON ges_comprobantes.IdCliente = ges_clientes.IdCliente\r\nINNER JOIN ges_locales ON ges_comprobantes.IdLocal = ges_locales.IdLocal\r\nINNER JOIN ges_usuarios ON ges_comprobantes.IdUsuario = ges_usuarios.IdUsuario\r\nINNER JOIN ges_comprobantesnum ON ges_comprobantes.IdComprobante = ges_comprobantesnum.IdComprobante\r\nINNER JOIN ges_comprobantestipo ON ges_comprobantesnum.IdTipoComprobante = ges_comprobantestipo.IdTipoComprobante\r\nINNER JOIN ges_suscripciones ON ges_comprobantes.IdSuscripcion = ges_suscripciones.IdSuscripcion\r\nINNER JOIN ges_suscripciontipo ON ges_suscripciones.IdTipoSuscripcion = ges_suscripciontipo.IdTipoSuscripcion\r\nWHERE ges_comprobantes.IdSuscripcion <> 0\r\nAND ges_comprobantes.IdLocal like ''%IDTIENDA%''\r\nAND DATE(ges_comprobantesnum.Fecha) >= ''%DESDE%''\r\nAND DATE(ges_comprobantesnum.Fecha) <= ''%HASTA%''\r\nAND ges_comprobantes.ImportePendiente ''%IMPORTE%''\r\nAND ges_clientes.NumeroFiscal like ''%DNICLIENTE%''', 'admin', 0, 'Suscripciones', 0);
;;;;;;

INSERT INTO `ges_listados` VALUES ('', 'DEUDAS', 'SELECT ges_locales.NombreComercial as Local, DATE_FORMAT(ges_comprobantes.FechaComprobante,''%d/%m/%y %H:%i'') as ''Fecha Emisión'',IF(ges_clientes.TipoCliente = ''Empresa'',ges_clientes.NombreLegal,ges_clientes.NombreComercial) as Cliente, CONCAT(ges_comprobantes.SerieComprobante,''-'',ges_comprobantes.NComprobante) as Código,CONCAT(ges_comprobantestipo.Serie,'' - '',ges_comprobantesnum.NumeroComprobante) as ''Serie-Nro'', ges_comprobantestipo.TipoComprobante as Comprobante, ROUND(ges_comprobantes.TotalImporte,2) as Importe, ROUND(ges_comprobantes.ImportePendiente,2) as Pendiente, ges_comprobantes.Cobranza as ''Estado Cobranza'', DATE_FORMAT(ges_comprobantes.PlazoPago,''%d/%m/%Y'') as ''Plazo Pago'', ges_comprobantes.Observaciones\r\nFROM ges_comprobantes\r\nINNER JOIN ges_locales ON ges_comprobantes.IdLocal = ges_locales.IdLocal\r\nINNER JOIN ges_comprobantesnum ON ges_comprobantes.IdComprobante =  ges_comprobantesnum.IdComprobante\r\nINNER JOIN ges_comprobantestipo ON ges_comprobantesnum.IdTipoComprobante = ges_comprobantestipo.IdTipoComprobante \r\nINNER JOIN ges_clientes ON ges_comprobantes.IdCliente = ges_clientes.IdCliente \r\nWHERE ges_comprobantes.Eliminado = 0\r\nAND ges_comprobantes.ImportePendiente > 0\r\nAND ges_comprobantestipo.TipoComprobante IN (''Factura'',''Boleta'',''Ticket'',''Albaran'')\r\nAND ges_comprobantesnum.Status <> ''Anulado''\r\nAND DATE(ges_comprobantesnum.Fecha) >= ''%DESDE%''\r\nAND DATE(ges_comprobantesnum.Fecha) <= ''%HASTA%''\r\nAND ges_comprobantes.IdLocal  like ''%IDTIENDA%''\r\nAND ges_comprobantestipo.TipoComprobante like ''%TIPOCOMPROBANTE%''\r\nAND ges_comprobantes.Cobranza like ''%COBRANZA%''\r\n''%TIPOVENTATPV%''', 'admin', 0, 'Ventas', 0);
;;;;;;

INSERT INTO `ges_listados` VALUES ('', 'DEUDAS CONSOLIDADO', 'SELECT ges_locales.NombreComercial as Local, IF(ges_clientes.TipoCliente = ''Empresa'',ges_clientes.NombreLegal,ges_clientes.NombreComercial) as Cliente,  ROUND(SUM(ges_comprobantes.TotalImporte),2) as Importe, ROUND(SUM(ges_comprobantes.ImportePendiente),2) as Pendiente\r\nFROM ges_comprobantes\r\nINNER JOIN ges_locales ON ges_comprobantes.IdLocal = ges_locales.IdLocal\r\nINNER JOIN ges_comprobantesnum ON ges_comprobantes.IdComprobante =  ges_comprobantesnum.IdComprobante\r\nINNER JOIN ges_comprobantestipo ON ges_comprobantesnum.IdTipoComprobante = ges_comprobantestipo.IdTipoComprobante \r\nINNER JOIN ges_clientes ON ges_comprobantes.IdCliente = ges_clientes.IdCliente \r\nWHERE ges_comprobantes.Eliminado = 0\r\nAND ges_comprobantes.ImportePendiente > 0\r\nAND ges_comprobantestipo.TipoComprobante IN (''Factura'',''Boleta'',''Ticket'',''Albaran'')\r\nAND ges_comprobantesnum.Status <> ''Anulado''\r\nAND DATE(ges_comprobantesnum.Fecha) >= ''%DESDE%''\r\nAND DATE(ges_comprobantesnum.Fecha) <= ''%HASTA%''\r\nAND ges_comprobantes.IdLocal  like ''%IDTIENDA%''\r\nAND ges_comprobantes.TipoVentaOperacion like ''%TIPOVENTAOP%''\r\nAND ges_comprobantes.Cobranza like ''%COBRANZA%''\r\nAND ges_comprobantestipo.TipoComprobante like ''%TIPOCOMPROBANTE%''\r\nGROUP BY ges_comprobantes.IdCliente\r\nORDER BY Cliente', 'TPV', 0, 'Ventas', 0);
;;;;;;

INSERT INTO `ges_listados` VALUES ('', 'CONSULTAR GUIAS', 'SELECT ges_proveedores.NombreComercial as Proveedor, ges_comprobantesprov.TipoComprobante as Comprobante, ges_comprobantesprov.Codigo as ''Código'', ges_comprobantesprov.CodigoAlbaran as ''Código Guías'', ges_comprobantesprov.TotalImporte as Importe, ges_comprobantesprov.ImporteFlete as Flete, ges_comprobantesprov.ImportePendiente as Pendiente, ges_comprobantesprov.Observaciones, ges_usuarios.Identificacion as Usuario \r\nFROM ges_comprobantesprov \r\nINNER JOIN ges_proveedores ON ges_comprobantesprov.IdProveedor = ges_proveedores.IdProveedor\r\nINNER JOIN ges_usuarios ON ges_comprobantesprov.IdUsuario = ges_usuarios.IdUsuario\r\nWHERE ges_comprobantesprov.TipoComprobante = ''Factura'' \r\nAND ges_proveedores.IdProveedor like ''%IDPROVEEDOR%''\r\nAND ges_comprobantesprov.Codigo like ''%%CODIGOCOMPROBANTE%%''', 'admin', 0, 'Compras', 0);
;;;;;;

INSERT INTO `ges_listados` VALUES ('', 'DEVOLUCIONES', 'SELECT  ges_locales.NombreComercial As Local,ges_comprobantesdet.CodigoBarras as CB,CONCAT(ges_productos_idioma.Descripcion,'' '',Marca,'' '',ges_comprobantesdet.Color,'' '',ges_comprobantesdet.Talla,'' '',ges_laboratorios.NombreComercial) As Producto, ges_comprobantestipo.TipoComprobante as Comprobante,CONCAT(ges_comprobantes.SerieComprobante,''-'',ges_comprobantes.NComprobante) as Código, CONCAT(ges_comprobantestipo.Serie,''-'',ges_comprobantesnum.NumeroComprobante) as ''Serie-Nro'', ges_comprobantesdet.CantidadDevolucion as Devolución, ges_comprobantesdet.Precio, ges_clientes.NombreComercial as Cliente, ges_usuarios.Identificacion as Usuario\r\nFROM ges_comprobantesdet\r\nINNER JOIN ges_comprobantes ON ges_comprobantesdet.IdComprobante = ges_comprobantes.IdComprobante\r\nINNER JOIN ges_productos ON ges_comprobantesdet.IdProducto=ges_productos.IdProducto \r\nINNER JOIN ges_locales ON ges_comprobantes.IdLocal=ges_locales.IdLocal \r\nINNER JOIN ges_productos_idioma ON ges_productos.IdProdBase=ges_productos_idioma.IdProdBase \r\nINNER JOIN ges_marcas ON ges_marcas.IdMarca=ges_productos.IdMarca \r\nINNER JOIN ges_modelos ON ges_modelos.IdColor=ges_productos.IdColor \r\nINNER JOIN ges_detalles ON ges_detalles.IdTalla=ges_productos.IdTalla \r\nINNER JOIN ges_laboratorios ON ges_laboratorios.IdLaboratorio=ges_productos.IdLabHab \r\nINNER JOIN ges_comprobantesnum ON ges_comprobantes.IdComprobante = ges_comprobantesnum.IdComprobante \r\nINNER JOIN ges_comprobantestipo ON ges_comprobantesnum.IdTipoComprobante = ges_comprobantestipo.IdTipoComprobante\r\nINNER JOIN ges_clientes ON ges_comprobantes.IdCliente = ges_clientes.IdCliente\r\nINNER JOIN ges_usuarios ON ges_comprobantes.IdUsuario = ges_usuarios.IdUsuario\r\nWHERE ges_comprobantesdet.CantidadDevolucion > 0\r\nAND DATE(ges_comprobantes.FechaComprobante) >= ''%DESDE%''\r\nAND DATE(ges_comprobantes.FechaComprobante) <= ''%HASTA%''\r\nAND ges_locales.IdLocal like ''%IDTIENDA%''\r\nAND ges_comprobantestipo.TipoComprobante IN (''Factura'',''Boleta'',''Ticket'',''Albaran'')', 'admin', 0, 'Ventas', 0);
;;;;;;

INSERT INTO `ges_listados` VALUES ('', 'DEVOLUCIONES', 'SELECT  ges_locales.NombreComercial As Local,ges_comprobantesdet.CodigoBarras as CB,CONCAT(ges_productos_idioma.Descripcion,'' '',Marca,'' '',ges_comprobantesdet.Color,'' '',ges_comprobantesdet.Talla,'' '',ges_laboratorios.NombreComercial) As Producto, ges_comprobantestipo.TipoComprobante as Comprobante, CONCAT(ges_comprobantes.SerieComprobante,''-'',ges_comprobantes.NComprobante) as Código, CONCAT(ges_comprobantestipo.Serie,''-'',ges_comprobantesnum.NumeroComprobante) as ''Serie-Nro'', ges_comprobantesdet.CantidadDevolucion as Devolución, ges_comprobantesdet.Precio, ges_clientes.NombreComercial as Cliente, ges_usuarios.Identificacion as Usuario\r\nFROM ges_comprobantesdet\r\nINNER JOIN ges_comprobantes ON ges_comprobantesdet.IdComprobante = ges_comprobantes.IdComprobante\r\nINNER JOIN ges_productos ON ges_comprobantesdet.IdProducto=ges_productos.IdProducto \r\nINNER JOIN ges_locales ON ges_comprobantes.IdLocal=ges_locales.IdLocal \r\nINNER JOIN ges_productos_idioma ON ges_productos.IdProdBase=ges_productos_idioma.IdProdBase \r\nINNER JOIN ges_marcas ON ges_marcas.IdMarca=ges_productos.IdMarca \r\nINNER JOIN ges_modelos ON ges_modelos.IdColor=ges_productos.IdColor \r\nINNER JOIN ges_detalles ON ges_detalles.IdTalla=ges_productos.IdTalla \r\nINNER JOIN ges_laboratorios ON ges_laboratorios.IdLaboratorio=ges_productos.IdLabHab \r\nINNER JOIN ges_comprobantesnum ON ges_comprobantes.IdComprobante = ges_comprobantesnum.IdComprobante \r\nINNER JOIN ges_comprobantestipo ON ges_comprobantesnum.IdTipoComprobante = ges_comprobantestipo.IdTipoComprobante\r\nINNER JOIN ges_clientes ON ges_comprobantes.IdCliente = ges_clientes.IdCliente\r\nINNER JOIN ges_usuarios ON ges_comprobantes.IdUsuario = ges_usuarios.IdUsuario\r\nWHERE ges_comprobantesdet.CantidadDevolucion > 0\r\nAND DATE(ges_comprobantes.FechaComprobante) >= ''%DESDE%''\r\nAND DATE(ges_comprobantes.FechaComprobante) <= ''%HASTA%''\r\nAND ges_locales.IdLocal like ''%IDTIENDA%''\r\nAND ges_comprobantestipo.TipoComprobante IN (''Factura'',''Boleta'',''Ticket'',''Albaran'')', 'TPV', 0, 'Ventas', 0);
;;;;;;

INSERT INTO `ges_listados` VALUES ('', 'STOCK CONSOLIDADO', 'SELECT  CodigoBarras As ''Código Barras'',Referencia, CONCAT(ges_productos_idioma.Descripcion,'' '', Marca,'' '', Color,'' '', Talla,'' '', ges_laboratorios.NombreComercial) As Producto, SUM(Unidades) as Unidades, ROUND(AVG(CostoUnitario),2) as Costo,  ROUND(SUM(Unidades)*AVG(CostoUnitario),2) as Importe\r\nFROM ges_almacenes INNER JOIN ges_productos ON ges_almacenes.IdProducto = ges_productos.IdProducto \r\nINNER JOIN ges_productos_idioma ON ges_productos.IdProdBase = ges_productos_idioma.IdProdBase \r\nINNER JOIN ges_marcas ON ges_marcas.IdMarca = ges_productos.IdMarca \r\nINNER JOIN ges_modelos ON ges_modelos.IdColor = ges_productos.IdColor\r\nINNER JOIN ges_detalles on ges_detalles.IdTalla = ges_productos.IdTalla\r\nINNER JOIN ges_laboratorios ON ges_laboratorios.IdLaboratorio = ges_productos.IdLabHab \r\nWHERE  ges_almacenes.Unidades > 0\r\nAND ges_almacenes.Eliminado = 0 \r\nGROUP BY ges_productos.IdProducto\r\nORDER BY ges_productos_idioma.Descripcion', 'admin', 0, 'Productos', 0);
;;;;;;

;;;;;;
INSERT INTO `ges_listados` VALUES ('', 'HISTORIAL DE ACCESOS', 'SELECT ges_locales.NombreComercial as Local,ges_usuarios.Nombre as ''Usuario'', DATE_FORMAT(ges_loginlog.FechaInicio,''%d/%m/%Y %H:%i'') as ''Fecha Acceso'', IF(DATE_FORMAT(ges_loginlog.FechaFin,''%e %b %Y'') IS NULL,'' '',DATE_FORMAT(ges_loginlog.FechaFin,''%d/%m/%Y %H:%i'')) as ''Fecha Salida'', IpAcceso as IP\r\nFROM ges_loginlog\r\nINNER JOIN ges_usuarios ON ges_loginlog.IdUsuario = ges_usuarios.IdUsuario \r\nINNER JOIN ges_locales ON ges_loginlog.IdLocal = ges_locales.IdLocal\r\nWHERE ges_loginlog.Eliminado = 0\r\nAND DATE(ges_loginlog.FechaInicio) >= ''%DESDE%''\r\nAND DATE(ges_loginlog.FechaInicio) <= ''%HASTA%''\r\nAND ges_loginlog.IdLocal like ''%IDTIENDA%''\r\nAND ges_usuarios.IdUsuario like ''%IDUSUARIO%''\r\nAND ges_usuarios.IdUsuario > 2\r\nORDER BY ges_locales.IdLocal ASC,ges_loginlog.IdLoginLog ASC', 'admin', 0, 'Listas', 0);
;;;;;;

;;;;;;
INSERT INTO `ges_listados` VALUES ('', 'PRESUPUESTOS', 'SELECT ges_locales.NombreComercial as Local,ges_usuarios.Nombre as Usuario, ges_presupuestos.TipoPresupuesto as Presupuesto, COUNT(ges_presupuestos.IdUsuarioRegistro) as Cantidad, ROUND(SUM(ges_presupuestos.TotalImporte),2) as Importe,\r\nges_presupuestos.Status as Estado\r\nFROM ges_presupuestos\r\nINNER JOIN ges_locales ON ges_presupuestos.IdLocal = ges_locales.IdLocal\r\nINNER JOIN ges_clientes ON ges_presupuestos.IdCliente = ges_clientes.IdCliente \r\nINNER JOIN ges_usuarios ON ges_presupuestos.IdUsuarioRegistro = ges_usuarios.IdUsuario\r\nWHERE ges_presupuestos.Eliminado = 0\r\nAND ges_presupuestos.Status IN (''Pendiente'',''Confirmado'',''Vencido'',''Cancelado'')\r\nAND DATE(ges_presupuestos.FechaPresupuesto) >= ''%DESDE%''\r\nAND DATE(ges_presupuestos.FechaPresupuesto) <= ''%HASTA%''\r\nAND ges_presupuestos.IdLocal  like ''%IDTIENDA%''\r\nAND ges_presupuestos.TipoPresupuesto like ''%PRESUPUESTOVENTA%''\r\nAND ges_presupuestos.Status like ''%ESTADOPRESUPUESTO%''\r\nGROUP BY ges_presupuestos.IdUsuarioRegistro,ges_presupuestos.TipoPresupuesto,ges_presupuestos.Status\r\nORDER BY ges_usuarios.Nombre ASC', 'admin', 0, 'Ventas', 0);
;;;;;;

;;;;;;
INSERT INTO `ges_listados` VALUES ('', 'STOCK POR REFERENCIA', 'SELECT  ges_locales.NombreComercial As Local,ges_productos.Referencia, CONCAT(ges_productos_idioma.Descripcion,'' '', Marca,'' '', ges_laboratorios.NombreComercial) As Producto, SUM(Unidades) as Unidades \r\nFROM ges_almacenes INNER JOIN ges_productos ON ges_almacenes.IdProducto = ges_productos.IdProducto \r\nINNER JOIN ges_locales ON ges_almacenes.IdLocal = ges_locales.IdLocal\r\nINNER JOIN ges_productos_idioma ON ges_productos.IdProdBase = ges_productos_idioma.IdProdBase \r\nINNER JOIN ges_marcas ON ges_marcas.IdMarca = ges_productos.IdMarca \r\nINNER JOIN ges_laboratorios ON ges_laboratorios.IdLaboratorio = ges_productos.IdLabHab \r\nINNER JOIN ges_familias ON ges_productos.IdFamilia = ges_familias.IdFamilia\r\nWHERE  ges_almacenes.Unidades > 0\r\nAND ges_almacenes.Eliminado = 0 \r\nAND ges_locales.IdLocal like ''%IDTIENDA%''\r\nAND ges_familias.IdFamilia like ''%IDFAMILIA%''\r\nGROUP BY ges_productos.Referencia \r\nORDER BY ges_productos_idioma.Descripcion;', 'admin', 0, 'Productos', 0);
;;;;;;

;;;;;;
INSERT INTO `ges_listados` VALUES ('', 'DEUDAS CONSOLIDADO', 'SELECT ges_locales.NombreComercial as Local, IF(ges_clientes.TipoCliente = ''Empresa'',ges_clientes.NombreLegal,ges_clientes.NombreComercial) as Cliente,  ROUND(SUM(ges_comprobantes.TotalImporte),2) as Importe, ROUND(SUM(ges_comprobantes.ImportePendiente),2) as Pendiente\r\nFROM ges_comprobantes\r\nINNER JOIN ges_locales ON ges_comprobantes.IdLocal = ges_locales.IdLocal\r\nINNER JOIN ges_comprobantesnum ON ges_comprobantes.IdComprobante =  ges_comprobantesnum.IdComprobante\r\nINNER JOIN ges_comprobantestipo ON ges_comprobantesnum.IdTipoComprobante = ges_comprobantestipo.IdTipoComprobante \r\nINNER JOIN ges_clientes ON ges_comprobantes.IdCliente = ges_clientes.IdCliente \r\nWHERE ges_comprobantes.Eliminado = 0\r\nAND ges_comprobantes.ImportePendiente > 0\r\nAND ges_comprobantestipo.TipoComprobante IN (''Factura'',''Boleta'',''Ticket'',''Albaran'')\r\nAND ges_comprobantesnum.Status <> ''Anulado''\r\nAND DATE(ges_comprobantesnum.Fecha) >= ''%DESDE%''\r\nAND DATE(ges_comprobantesnum.Fecha) <= ''%HASTA%''\r\nAND ges_comprobantes.IdLocal  like ''%IDTIENDA%''\r\nAND ges_comprobantes.TipoVentaOperacion  like ''%TIPOVENTAOP%''\r\nAND ges_comprobantestipo.TipoComprobante like ''%TIPOCOMPROBANTE%''\r\n''%TIPOVENTATPV%''\r\nAND ges_comprobantes.Cobranza like ''%COBRANZA%''\r\nGROUP BY ges_comprobantes.IdCliente\r\nORDER BY Cliente', 'Admin', 0, 'Ventas', 0);
;;;;;;

;;;;;;
INSERT INTO `ges_listados` VALUES ('', 'POR CLIENTES CONSOLIDADO', 'SELECT ges_locales.NombreComercial as Local, ges_clientes.TipoCliente AS ''Tipo Cliente'', IF(ges_clientes.TipoCliente = ''Empresa'',ges_clientes.NombreLegal,ges_clientes.NombreComercial) as Cliente, ges_clientes.NumeroFiscal as ''DNI/RUC'', ROUND(SUM(ges_comprobantes.TotalImporte),2) as ''Importe %SML%'', ROUND(SUM(ges_comprobantes.ImportePendiente),2) as ''Pendiente %SML%''\r\nFROM ges_comprobantes \r\nINNER JOIN ges_comprobantesnum ON ges_comprobantes.IdComprobante = ges_comprobantesnum.IdComprobante \r\nINNER JOIN ges_comprobantestipo ON ges_comprobantesnum.IdTipoComprobante = ges_comprobantestipo.IdTipoComprobante \r\nINNER JOIN ges_locales ON ges_comprobantes.IdLocal = ges_locales.IdLocal\r\nINNER JOIN ges_clientes ON ges_comprobantes.IdCliente = ges_clientes.IdCliente\r\nAND DATE(ges_comprobantes.FechaComprobante) >= ''%DESDE%'' \r\nAND DATE(ges_comprobantes.FechaComprobante) <= ''%HASTA%'' \r\nAND ges_comprobantes.IdLocal like ''%IDTIENDA%'' \r\nAND ges_clientes.TipoCliente like ''%TIPOCLIENTE%''\r\nAND ges_comprobantestipo.TipoComprobante IN (''Factura'',''Boleta'',''Ticket'',''Albaran'') \r\nAND ges_comprobantesnum.Status <> ''Anulado'' \r\nAND ges_comprobantes.Eliminado = 0 \r\nAND ges_clientes.TipoCliente <> ''Interno''\r\nGROUP BY ges_clientes.IdCliente \r\nORDER BY ges_locales.IdLocal,''Importe %SML%'' DESC', 'admin', 0, 'Ventas', 0);
;;;;;;

;;;;;;
INSERT INTO `ges_listados` VALUES ('', 'MOVIMIENTOS CUENTA BANCARIA TPV', 'SELECT ges_locales.NombreComercial as Local, ges_cuentasbancarias.EntidadFinanciera as ''Entidad Financiera'',ges_cuentasbancarias.NumeroCuenta as ''Cuenta Bancaria'', ges_clientes.NombreComercial as Cliente, DATE_FORMAT(ges_dinero_movimientos.FechaPago, ''%d/%m/%Y %H:%i'') as ''Fecha Pago'', ges_cobrosclientedoc.CodOperacion as ''Código Operación'', ges_dinero_movimientos.Importe, ges_cobrosclientedoc.Observaciones, ges_usuarios.Identificacion as Usuario \r\nFROM ges_cobrosclientedoc \r\nINNER JOIN ges_locales ON ges_cobrosclientedoc.IdLocal = ges_locales.IdLocal\r\nINNER JOIN ges_usuarios ON ges_cobrosclientedoc.IdUsuario = ges_usuarios.IdUsuario\r\nINNER JOIN ges_cuentasbancarias ON ges_cobrosclientedoc.IdCuentaBancaria = ges_cuentasbancarias.IdCuentaBancaria\r\nINNER JOIN ges_dinero_movimientos ON ges_cobrosclientedoc.IdOperacionCaja = ges_dinero_movimientos.IdOperacionCaja\r\nINNER JOIN ges_comprobantes ON ges_dinero_movimientos.IdComprobante = ges_comprobantes.IdComprobante\r\nINNER JOIN ges_clientes ON ges_comprobantes.IdCliente = ges_clientes.IdCliente\r\nINNER JOIN ges_comprobantesnum ON ges_comprobantes.IdComprobante = ges_comprobantesnum.IdComprobante\r\nWHERE ges_comprobantes.Eliminado = 0\r\nAND ges_comprobantesnum.Status <> ''Anulado''\r\nAND DATE(ges_dinero_movimientos.FechaPago) >= ''%DESDE%''\r\nAND DATE(ges_dinero_movimientos.FechaPago) <= ''%HASTA%''\r\nAND ges_locales.IdLocal like ''%IDTIENDA%''\r\nAND ges_cuentasbancarias.IdCuentaBancaria like ''%CUENTABANCARIA%''\r\nORDER BY ges_cuentasbancarias.EntidadFinanciera ASC, ges_cuentasbancarias.NumeroCuenta ASC\r\n', 'admin', 0, 'Finanzas', 0);
;;;;;;